//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yamon.Module.Weather.WebApi.ZDZServices {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZDZServices.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllZdzInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllZdzInfo(string mapType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLastestZdzData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetLastestZdzData(string dataType, string zdzType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetZdzHistoryList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetZdzHistoryList(string stationID, string fromTime, string toTime, string dataType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLastestZdzInfoByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLastestZdzInfoByID(string stationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDanYaoShuTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDanYaoShuTable(string ID, string dataField, string dataTable, string fromTime, string toTime, string directionField);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDanZhanDianTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDanZhanDianTable(string ID, string fromTime, string toTime, string dateType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPairsCurveByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPairsCurveByID(string ID, string fromTime, string toTime, string leftFields, string leftTable, string rightFields, string rightTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLastestAndHistoryData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLastestAndHistoryData(string stationID, string fromTime, string toTime, string dataType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPairsCurveByIDandType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPairsCurveByIDandType(string ID, string fromTime, string toTime, string leftFields, string leftTable, string rightFields, string rightTable, string dataType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetZdzAlarm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetZdzAlarm(string fromTime, string toTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetZdzStatisticInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetZdzStatisticInfo(string fromTime, string toTime, string dataType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBlpZdz", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllBlpZdz();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetUserInfo(string name, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserOpertationLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetUserOpertationLog(string operationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecoderUserLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int RecoderUserLog(string operationType, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFourBuyoData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetFourBuyoData();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Yamon.Module.Weather.WebApi.ZDZServices.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Yamon.Module.Weather.WebApi.ZDZServices.ServiceSoap>, Yamon.Module.Weather.WebApi.ZDZServices.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetAllZdzInfo(string mapType) {
            return base.Channel.GetAllZdzInfo(mapType);
        }
        
        public System.Data.DataTable GetLastestZdzData(string dataType, string zdzType) {
            return base.Channel.GetLastestZdzData(dataType, zdzType);
        }
        
        public System.Data.DataTable GetZdzHistoryList(string stationID, string fromTime, string toTime, string dataType) {
            return base.Channel.GetZdzHistoryList(stationID, fromTime, toTime, dataType);
        }
        
        public System.Data.DataSet GetLastestZdzInfoByID(string stationID) {
            return base.Channel.GetLastestZdzInfoByID(stationID);
        }
        
        public System.Data.DataSet GetDanYaoShuTable(string ID, string dataField, string dataTable, string fromTime, string toTime, string directionField) {
            return base.Channel.GetDanYaoShuTable(ID, dataField, dataTable, fromTime, toTime, directionField);
        }
        
        public System.Data.DataSet GetDanZhanDianTable(string ID, string fromTime, string toTime, string dateType) {
            return base.Channel.GetDanZhanDianTable(ID, fromTime, toTime, dateType);
        }
        
        public System.Data.DataTable GetPairsCurveByID(string ID, string fromTime, string toTime, string leftFields, string leftTable, string rightFields, string rightTable) {
            return base.Channel.GetPairsCurveByID(ID, fromTime, toTime, leftFields, leftTable, rightFields, rightTable);
        }
        
        public System.Data.DataSet GetLastestAndHistoryData(string stationID, string fromTime, string toTime, string dataType) {
            return base.Channel.GetLastestAndHistoryData(stationID, fromTime, toTime, dataType);
        }
        
        public System.Data.DataTable GetPairsCurveByIDandType(string ID, string fromTime, string toTime, string leftFields, string leftTable, string rightFields, string rightTable, string dataType) {
            return base.Channel.GetPairsCurveByIDandType(ID, fromTime, toTime, leftFields, leftTable, rightFields, rightTable, dataType);
        }
        
        public System.Data.DataTable GetZdzAlarm(string fromTime, string toTime) {
            return base.Channel.GetZdzAlarm(fromTime, toTime);
        }
        
        public System.Data.DataTable GetZdzStatisticInfo(string fromTime, string toTime, string dataType) {
            return base.Channel.GetZdzStatisticInfo(fromTime, toTime, dataType);
        }
        
        public System.Data.DataSet GetAllBlpZdz() {
            return base.Channel.GetAllBlpZdz();
        }
        
        public System.Data.DataTable GetUserInfo(string name, string pwd) {
            return base.Channel.GetUserInfo(name, pwd);
        }
        
        public System.Data.DataTable GetUserOpertationLog(string operationType) {
            return base.Channel.GetUserOpertationLog(operationType);
        }
        
        public int RecoderUserLog(string operationType, string username) {
            return base.Channel.RecoderUserLog(operationType, username);
        }
        
        public System.Data.DataTable GetFourBuyoData() {
            return base.Channel.GetFourBuyoData();
        }
    }
}
