#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage.Entity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/zdz/Views/zdzinstantHistory/_/Create.cshtml")]
    public partial class _Areas_zdz_Views_zdzinstantHistory___Create_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_zdz_Views_zdzinstantHistory___Create_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------
    ViewBag.Title="新建自动历史站数据";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #F6F6F6; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/zdz/zdzinstantHistory/Create\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_ID\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">编号：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ID\"");

WriteLiteral(" name=\"ID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 822), Tuple.Create("\"", 841)
            
            #line 22 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 830), Tuple.Create<System.Object, System.Int32>(Model.ID
            
            #line default
            #line hidden
, 830), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">站名：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"station\"");

WriteLiteral(" name=\"station\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1027), Tuple.Create("\"", 1051)
            
            #line 25 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1035), Tuple.Create<System.Object, System.Int32>(Model.station
            
            #line default
            #line hidden
, 1035), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_sun_rad\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">太阳辐射：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"sun_rad\"");

WriteLiteral(" name=\"sun_rad\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1259), Tuple.Create("\"", 1283)
            
            #line 30 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1267), Tuple.Create<System.Object, System.Int32>(Model.sun_rad
            
            #line default
            #line hidden
, 1267), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">平均太阳辐射：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"aver_rad\"");

WriteLiteral(" name=\"aver_rad\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1458), Tuple.Create("\"", 1483)
            
            #line 33 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1466), Tuple.Create<System.Object, System.Int32>(Model.aver_rad
            
            #line default
            #line hidden
, 1466), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_rad\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最高太阳辐射：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_rad\"");

WriteLiteral(" name=\"max_rad\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1692), Tuple.Create("\"", 1716)
            
            #line 38 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1700), Tuple.Create<System.Object, System.Int32>(Model.max_rad
            
            #line default
            #line hidden
, 1700), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最高太阳辐射时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_rad_time\"");

WriteLiteral(" name=\"max_rad_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1901), Tuple.Create("\"", 1930)
            
            #line 41 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1909), Tuple.Create<System.Object, System.Int32>(Model.max_rad_time
            
            #line default
            #line hidden
, 1909), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_uv\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">uv：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"uv\"");

WriteLiteral(" name=\"uv\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2120), Tuple.Create("\"", 2139)
            
            #line 46 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2128), Tuple.Create<System.Object, System.Int32>(Model.uv
            
            #line default
            #line hidden
, 2128), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">aver_uv：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"aver_uv\"");

WriteLiteral(" name=\"aver_uv\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2313), Tuple.Create("\"", 2337)
            
            #line 49 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2321), Tuple.Create<System.Object, System.Int32>(Model.aver_uv
            
            #line default
            #line hidden
, 2321), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_uv\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_uv：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_uv\"");

WriteLiteral(" name=\"max_uv\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2543), Tuple.Create("\"", 2566)
            
            #line 54 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2551), Tuple.Create<System.Object, System.Int32>(Model.max_uv
            
            #line default
            #line hidden
, 2551), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_uv_time：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_uv_time\"");

WriteLiteral(" name=\"max_uv_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2752), Tuple.Create("\"", 2780)
            
            #line 57 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2760), Tuple.Create<System.Object, System.Int32>(Model.max_uv_time
            
            #line default
            #line hidden
, 2760), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_instant_vis\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">能见度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"instant_vis\"");

WriteLiteral(" name=\"instant_vis\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2998), Tuple.Create("\"", 3026)
            
            #line 62 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3006), Tuple.Create<System.Object, System.Int32>(Model.instant_vis
            
            #line default
            #line hidden
, 3006), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"9\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">十分钟平均能见度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ten_aver_vis\"");

WriteLiteral(" name=\"ten_aver_vis\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3211), Tuple.Create("\"", 3240)
            
            #line 65 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3219), Tuple.Create<System.Object, System.Int32>(Model.ten_aver_vis
            
            #line default
            #line hidden
, 3219), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"9\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_two_aver_wd\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">两分钟平均风向：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"two_aver_wd\"");

WriteLiteral(" name=\"two_aver_wd\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3462), Tuple.Create("\"", 3490)
            
            #line 70 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3470), Tuple.Create<System.Object, System.Int32>(Model.two_aver_wd
            
            #line default
            #line hidden
, 3470), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"6\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">两分钟平均风力：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"two_aver_ws\"");

WriteLiteral(" name=\"two_aver_ws\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3672), Tuple.Create("\"", 3700)
            
            #line 73 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3680), Tuple.Create<System.Object, System.Int32>(Model.two_aver_ws
            
            #line default
            #line hidden
, 3680), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_ten_aver_wd\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">十分钟平均风向：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ten_aver_wd\"");

WriteLiteral(" name=\"ten_aver_wd\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3922), Tuple.Create("\"", 3950)
            
            #line 78 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3930), Tuple.Create<System.Object, System.Int32>(Model.ten_aver_wd
            
            #line default
            #line hidden
, 3930), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"6\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">十分钟平均风力：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ten_aver_ws\"");

WriteLiteral(" name=\"ten_aver_ws\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4132), Tuple.Create("\"", 4160)
            
            #line 81 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 4140), Tuple.Create<System.Object, System.Int32>(Model.ten_aver_ws
            
            #line default
            #line hidden
, 4140), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_date\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">数据时次：</td><td>&nbsp;    <input");

WriteLiteral(" class=\"Wdate\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" onClick=\"WdatePicker({dateFmt:\'yyyy-MM-dd HH:mm:ss\'})\"");

WriteLiteral(" id=\"date\"");

WriteLiteral(" name=\"date\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4429), Tuple.Create("\"", 4502)
            
            #line 85 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
                                                                                  , Tuple.Create(Tuple.Create("", 4437), Tuple.Create<System.Object, System.Int32>(Model.date==null?"":Model.date.ToString("yyyy-MM-dd HH:mm:ss")
            
            #line default
            #line hidden
, 4437), false)
);

WriteLiteral(" style=\"width:135px;\"");

WriteLiteral(">\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">十分钟最大风向：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ten_max_wd\"");

WriteLiteral(" name=\"ten_max_wd\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4631), Tuple.Create("\"", 4658)
            
            #line 88 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 4639), Tuple.Create<System.Object, System.Int32>(Model.ten_max_wd
            
            #line default
            #line hidden
, 4639), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"6\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_ten_max_ws\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">十分钟最大风力：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ten_max_ws\"");

WriteLiteral(" name=\"ten_max_ws\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4877), Tuple.Create("\"", 4904)
            
            #line 93 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 4885), Tuple.Create<System.Object, System.Int32>(Model.ten_max_ws
            
            #line default
            #line hidden
, 4885), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">十分钟最大风力时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ten_maxws_time\"");

WriteLiteral(" name=\"ten_maxws_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5094), Tuple.Create("\"", 5125)
            
            #line 96 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 5102), Tuple.Create<System.Object, System.Int32>(Model.ten_maxws_time
            
            #line default
            #line hidden
, 5102), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_instant_wd\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">瞬时风向：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"instant_wd\"");

WriteLiteral(" name=\"instant_wd\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5341), Tuple.Create("\"", 5368)
            
            #line 101 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 5349), Tuple.Create<System.Object, System.Int32>(Model.instant_wd
            
            #line default
            #line hidden
, 5349), false)
);

WriteLiteral(" class=\"easyui-numberbox\"");

WriteLiteral(" min=\"0\"");

WriteLiteral(" max=\"1000\"");

WriteLiteral("  precision=\"0\"");

WriteLiteral(" style=\"width:200px;\"");

WriteLiteral("/>\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">瞬时风力：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"instant_ws\"");

WriteLiteral(" name=\"instant_ws\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5554), Tuple.Create("\"", 5581)
            
            #line 104 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 5562), Tuple.Create<System.Object, System.Int32>(Model.instant_ws
            
            #line default
            #line hidden
, 5562), false)
);

WriteLiteral(" class=\"easyui-numberbox\"");

WriteLiteral(" min=\"0\"");

WriteLiteral(" max=\"1000\"");

WriteLiteral("  precision=\"1\"");

WriteLiteral(" style=\"width:200px;\"");

WriteLiteral("/>\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_flu_wd\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_flu_wd：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_flu_wd\"");

WriteLiteral(" name=\"max_flu_wd\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5812), Tuple.Create("\"", 5839)
            
            #line 109 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 5820), Tuple.Create<System.Object, System.Int32>(Model.max_flu_wd
            
            #line default
            #line hidden
, 5820), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"6\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_flu_ws：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_flu_ws\"");

WriteLiteral(" name=\"max_flu_ws\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6022), Tuple.Create("\"", 6049)
            
            #line 112 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 6030), Tuple.Create<System.Object, System.Int32>(Model.max_flu_ws
            
            #line default
            #line hidden
, 6030), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_flu_time\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_flu_time：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_flu_time\"");

WriteLiteral(" name=\"max_flu_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6279), Tuple.Create("\"", 6308)
            
            #line 117 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 6287), Tuple.Create<System.Object, System.Int32>(Model.max_flu_time
            
            #line default
            #line hidden
, 6287), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">一小时降雨量：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"one_rain\"");

WriteLiteral(" name=\"one_rain\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6483), Tuple.Create("\"", 6508)
            
            #line 120 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 6491), Tuple.Create<System.Object, System.Int32>(Model.one_rain
            
            #line default
            #line hidden
, 6491), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_temper\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">温度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"temper\"");

WriteLiteral(" name=\"temper\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6710), Tuple.Create("\"", 6733)
            
            #line 125 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 6718), Tuple.Create<System.Object, System.Int32>(Model.temper
            
            #line default
            #line hidden
, 6718), false)
);

WriteLiteral(" class=\"easyui-numberbox\"");

WriteLiteral(" min=\"0\"");

WriteLiteral(" max=\"1000\"");

WriteLiteral("  style=\"width:200px;\"");

WriteLiteral("/>\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最高温度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_temper\"");

WriteLiteral(" name=\"max_temper\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6905), Tuple.Create("\"", 6932)
            
            #line 128 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 6913), Tuple.Create<System.Object, System.Int32>(Model.max_temper
            
            #line default
            #line hidden
, 6913), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_temp_time\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最高温度时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_temp_time\"");

WriteLiteral(" name=\"max_temp_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7159), Tuple.Create("\"", 7189)
            
            #line 133 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 7167), Tuple.Create<System.Object, System.Int32>(Model.max_temp_time
            
            #line default
            #line hidden
, 7167), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最低温度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_temper\"");

WriteLiteral(" name=\"min_temper\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7366), Tuple.Create("\"", 7393)
            
            #line 136 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 7374), Tuple.Create<System.Object, System.Int32>(Model.min_temper
            
            #line default
            #line hidden
, 7374), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_min_temp_time\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最低温度时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_temp_time\"");

WriteLiteral(" name=\"min_temp_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7620), Tuple.Create("\"", 7650)
            
            #line 141 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 7628), Tuple.Create<System.Object, System.Int32>(Model.min_temp_time
            
            #line default
            #line hidden
, 7628), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">湿度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"rel_humi\"");

WriteLiteral(" name=\"rel_humi\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7821), Tuple.Create("\"", 7846)
            
            #line 144 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 7829), Tuple.Create<System.Object, System.Int32>(Model.rel_humi
            
            #line default
            #line hidden
, 7829), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"6\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_min_relhumi\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最小湿度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_relhumi\"");

WriteLiteral(" name=\"min_relhumi\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8065), Tuple.Create("\"", 8093)
            
            #line 149 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 8073), Tuple.Create<System.Object, System.Int32>(Model.min_relhumi
            
            #line default
            #line hidden
, 8073), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"6\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最小湿度时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_relhumi_time\"");

WriteLiteral(" name=\"min_relhumi_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8284), Tuple.Create("\"", 8317)
            
            #line 152 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 8292), Tuple.Create<System.Object, System.Int32>(Model.min_relhumi_time
            
            #line default
            #line hidden
, 8292), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_vap_press\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"vap_press\"");

WriteLiteral(" name=\"vap_press\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8526), Tuple.Create("\"", 8552)
            
            #line 157 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 8534), Tuple.Create<System.Object, System.Int32>(Model.vap_press
            
            #line default
            #line hidden
, 8534), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">露点：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"dew_point\"");

WriteLiteral(" name=\"dew_point\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8725), Tuple.Create("\"", 8751)
            
            #line 160 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 8733), Tuple.Create<System.Object, System.Int32>(Model.dew_point
            
            #line default
            #line hidden
, 8733), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_air_press\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">气压：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"air_press\"");

WriteLiteral(" name=\"air_press\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8962), Tuple.Create("\"", 8988)
            
            #line 165 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 8970), Tuple.Create<System.Object, System.Int32>(Model.air_press
            
            #line default
            #line hidden
, 8970), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最大气压：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_press\"");

WriteLiteral(" name=\"max_press\"");

WriteAttribute("value", Tuple.Create(" value=\"", 9163), Tuple.Create("\"", 9189)
            
            #line 168 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 9171), Tuple.Create<System.Object, System.Int32>(Model.max_press
            
            #line default
            #line hidden
, 9171), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_press_time\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最大气压时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_press_time\"");

WriteLiteral(" name=\"max_press_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 9419), Tuple.Create("\"", 9450)
            
            #line 173 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 9427), Tuple.Create<System.Object, System.Int32>(Model.max_press_time
            
            #line default
            #line hidden
, 9427), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最小气压：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_press\"");

WriteLiteral(" name=\"min_press\"");

WriteAttribute("value", Tuple.Create(" value=\"", 9625), Tuple.Create("\"", 9651)
            
            #line 176 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 9633), Tuple.Create<System.Object, System.Int32>(Model.min_press
            
            #line default
            #line hidden
, 9633), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_min_press_time\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最小气压时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_press_time\"");

WriteLiteral(" name=\"min_press_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 9881), Tuple.Create("\"", 9912)
            
            #line 181 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 9889), Tuple.Create<System.Object, System.Int32>(Model.min_press_time
            
            #line default
            #line hidden
, 9889), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">surf_temp：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"surf_temp\"");

WriteLiteral(" name=\"surf_temp\"");

WriteAttribute("value", Tuple.Create(" value=\"", 10092), Tuple.Create("\"", 10118)
            
            #line 184 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 10100), Tuple.Create<System.Object, System.Int32>(Model.surf_temp
            
            #line default
            #line hidden
, 10100), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_surf_temp\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_surf_temp：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_surf_temp\"");

WriteLiteral(" name=\"max_surf_temp\"");

WriteAttribute("value", Tuple.Create(" value=\"", 10352), Tuple.Create("\"", 10382)
            
            #line 189 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 10360), Tuple.Create<System.Object, System.Int32>(Model.max_surf_temp
            
            #line default
            #line hidden
, 10360), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_sutemp_time：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_sutemp_time\"");

WriteLiteral(" name=\"max_sutemp_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 10580), Tuple.Create("\"", 10612)
            
            #line 192 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 10588), Tuple.Create<System.Object, System.Int32>(Model.max_sutemp_time
            
            #line default
            #line hidden
, 10588), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_min_surf_temp\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">min_surf_temp：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_surf_temp\"");

WriteLiteral(" name=\"min_surf_temp\"");

WriteAttribute("value", Tuple.Create(" value=\"", 10846), Tuple.Create("\"", 10876)
            
            #line 197 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 10854), Tuple.Create<System.Object, System.Int32>(Model.min_surf_temp
            
            #line default
            #line hidden
, 10854), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">min_sutemp_time：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_sutemp_time\"");

WriteLiteral(" name=\"min_sutemp_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 11074), Tuple.Create("\"", 11106)
            
            #line 200 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 11082), Tuple.Create<System.Object, System.Int32>(Model.min_sutemp_time
            
            #line default
            #line hidden
, 11082), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 206 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
   Write(RenderPage("~/Areas/zdz/Views/zdzinstantHistory/Extend/Model_FormHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnSubmit\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-ok\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">确定</a>\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        取消\r\n    </a>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/My97DatePicker/WdatePicker.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/Utils.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        jQuery(function() {
            CheckConditions();
function CheckConditions(){
jQuery('fieldset').show(); 
jQuery(""fieldset"").each(function(){ 
if(jQuery('tr',this).length>0){
if(jQuery('tr:visible',this).length>0){jQuery(this).show()} else{jQuery(this).hide()}
}
});
}
;
        });
    </script>
");

WriteLiteral("    ");

            
            #line 234 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Create.cshtml"
Write(RenderPage("~/Areas/zdz/Views/zdzinstantHistory/Extend/Model_FormJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
