#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage.Entity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/zdz/Views/zdzinstantHistory/_/Edit.cshtml")]
    public partial class _Areas_zdz_Views_zdzinstantHistory___Edit_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_zdz_Views_zdzinstantHistory___Edit_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------
    ViewBag.Title="编辑自动历史站数据";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #F6F6F6; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/zdz/zdzinstantHistory/Edit\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_ID\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">编号：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ID\"");

WriteLiteral(" name=\"ID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 820), Tuple.Create("\"", 839)
            
            #line 22 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 828), Tuple.Create<System.Object, System.Int32>(Model.ID
            
            #line default
            #line hidden
, 828), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">站名：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"station\"");

WriteLiteral(" name=\"station\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1025), Tuple.Create("\"", 1049)
            
            #line 25 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1033), Tuple.Create<System.Object, System.Int32>(Model.station
            
            #line default
            #line hidden
, 1033), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_sun_rad\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">太阳辐射：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"sun_rad\"");

WriteLiteral(" name=\"sun_rad\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1257), Tuple.Create("\"", 1281)
            
            #line 30 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1265), Tuple.Create<System.Object, System.Int32>(Model.sun_rad
            
            #line default
            #line hidden
, 1265), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">平均太阳辐射：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"aver_rad\"");

WriteLiteral(" name=\"aver_rad\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1456), Tuple.Create("\"", 1481)
            
            #line 33 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1464), Tuple.Create<System.Object, System.Int32>(Model.aver_rad
            
            #line default
            #line hidden
, 1464), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_rad\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最高太阳辐射：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_rad\"");

WriteLiteral(" name=\"max_rad\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1690), Tuple.Create("\"", 1714)
            
            #line 38 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1698), Tuple.Create<System.Object, System.Int32>(Model.max_rad
            
            #line default
            #line hidden
, 1698), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最高太阳辐射时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_rad_time\"");

WriteLiteral(" name=\"max_rad_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1899), Tuple.Create("\"", 1928)
            
            #line 41 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1907), Tuple.Create<System.Object, System.Int32>(Model.max_rad_time
            
            #line default
            #line hidden
, 1907), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_uv\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">uv：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"uv\"");

WriteLiteral(" name=\"uv\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2118), Tuple.Create("\"", 2137)
            
            #line 46 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2126), Tuple.Create<System.Object, System.Int32>(Model.uv
            
            #line default
            #line hidden
, 2126), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">aver_uv：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"aver_uv\"");

WriteLiteral(" name=\"aver_uv\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2311), Tuple.Create("\"", 2335)
            
            #line 49 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2319), Tuple.Create<System.Object, System.Int32>(Model.aver_uv
            
            #line default
            #line hidden
, 2319), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_uv\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_uv：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_uv\"");

WriteLiteral(" name=\"max_uv\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2541), Tuple.Create("\"", 2564)
            
            #line 54 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2549), Tuple.Create<System.Object, System.Int32>(Model.max_uv
            
            #line default
            #line hidden
, 2549), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_uv_time：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_uv_time\"");

WriteLiteral(" name=\"max_uv_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2750), Tuple.Create("\"", 2778)
            
            #line 57 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2758), Tuple.Create<System.Object, System.Int32>(Model.max_uv_time
            
            #line default
            #line hidden
, 2758), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_instant_vis\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">能见度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"instant_vis\"");

WriteLiteral(" name=\"instant_vis\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2996), Tuple.Create("\"", 3024)
            
            #line 62 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 3004), Tuple.Create<System.Object, System.Int32>(Model.instant_vis
            
            #line default
            #line hidden
, 3004), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"9\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">十分钟平均能见度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ten_aver_vis\"");

WriteLiteral(" name=\"ten_aver_vis\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3209), Tuple.Create("\"", 3238)
            
            #line 65 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 3217), Tuple.Create<System.Object, System.Int32>(Model.ten_aver_vis
            
            #line default
            #line hidden
, 3217), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"9\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_two_aver_wd\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">两分钟平均风向：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"two_aver_wd\"");

WriteLiteral(" name=\"two_aver_wd\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3460), Tuple.Create("\"", 3488)
            
            #line 70 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 3468), Tuple.Create<System.Object, System.Int32>(Model.two_aver_wd
            
            #line default
            #line hidden
, 3468), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"6\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">两分钟平均风力：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"two_aver_ws\"");

WriteLiteral(" name=\"two_aver_ws\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3670), Tuple.Create("\"", 3698)
            
            #line 73 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 3678), Tuple.Create<System.Object, System.Int32>(Model.two_aver_ws
            
            #line default
            #line hidden
, 3678), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_ten_aver_wd\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">十分钟平均风向：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ten_aver_wd\"");

WriteLiteral(" name=\"ten_aver_wd\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3920), Tuple.Create("\"", 3948)
            
            #line 78 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 3928), Tuple.Create<System.Object, System.Int32>(Model.ten_aver_wd
            
            #line default
            #line hidden
, 3928), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"6\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">十分钟平均风力：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ten_aver_ws\"");

WriteLiteral(" name=\"ten_aver_ws\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4130), Tuple.Create("\"", 4158)
            
            #line 81 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 4138), Tuple.Create<System.Object, System.Int32>(Model.ten_aver_ws
            
            #line default
            #line hidden
, 4138), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_date\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">数据时次：</td><td>&nbsp;    <input");

WriteLiteral(" class=\"Wdate\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" onClick=\"WdatePicker({dateFmt:\'yyyy-MM-dd HH:mm:ss\'})\"");

WriteLiteral(" id=\"date\"");

WriteLiteral(" name=\"date\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4427), Tuple.Create("\"", 4500)
            
            #line 85 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
                                                                                  , Tuple.Create(Tuple.Create("", 4435), Tuple.Create<System.Object, System.Int32>(Model.date==null?"":Model.date.ToString("yyyy-MM-dd HH:mm:ss")
            
            #line default
            #line hidden
, 4435), false)
);

WriteLiteral(" style=\"width:135px;\"");

WriteLiteral(">\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">十分钟最大风向：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ten_max_wd\"");

WriteLiteral(" name=\"ten_max_wd\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4629), Tuple.Create("\"", 4656)
            
            #line 88 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 4637), Tuple.Create<System.Object, System.Int32>(Model.ten_max_wd
            
            #line default
            #line hidden
, 4637), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"6\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_ten_max_ws\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">十分钟最大风力：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ten_max_ws\"");

WriteLiteral(" name=\"ten_max_ws\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4875), Tuple.Create("\"", 4902)
            
            #line 93 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 4883), Tuple.Create<System.Object, System.Int32>(Model.ten_max_ws
            
            #line default
            #line hidden
, 4883), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">十分钟最大风力时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ten_maxws_time\"");

WriteLiteral(" name=\"ten_maxws_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5092), Tuple.Create("\"", 5123)
            
            #line 96 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5100), Tuple.Create<System.Object, System.Int32>(Model.ten_maxws_time
            
            #line default
            #line hidden
, 5100), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_instant_wd\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">瞬时风向：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"instant_wd\"");

WriteLiteral(" name=\"instant_wd\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5339), Tuple.Create("\"", 5366)
            
            #line 101 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5347), Tuple.Create<System.Object, System.Int32>(Model.instant_wd
            
            #line default
            #line hidden
, 5347), false)
);

WriteLiteral(" class=\"easyui-numberbox\"");

WriteLiteral(" min=\"0\"");

WriteLiteral(" max=\"1000\"");

WriteLiteral("  precision=\"0\"");

WriteLiteral(" style=\"width:200px;\"");

WriteLiteral("/>\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">瞬时风力：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"instant_ws\"");

WriteLiteral(" name=\"instant_ws\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5552), Tuple.Create("\"", 5579)
            
            #line 104 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5560), Tuple.Create<System.Object, System.Int32>(Model.instant_ws
            
            #line default
            #line hidden
, 5560), false)
);

WriteLiteral(" class=\"easyui-numberbox\"");

WriteLiteral(" min=\"0\"");

WriteLiteral(" max=\"1000\"");

WriteLiteral("  precision=\"1\"");

WriteLiteral(" style=\"width:200px;\"");

WriteLiteral("/>\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_flu_wd\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_flu_wd：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_flu_wd\"");

WriteLiteral(" name=\"max_flu_wd\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5810), Tuple.Create("\"", 5837)
            
            #line 109 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5818), Tuple.Create<System.Object, System.Int32>(Model.max_flu_wd
            
            #line default
            #line hidden
, 5818), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"6\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_flu_ws：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_flu_ws\"");

WriteLiteral(" name=\"max_flu_ws\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6020), Tuple.Create("\"", 6047)
            
            #line 112 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 6028), Tuple.Create<System.Object, System.Int32>(Model.max_flu_ws
            
            #line default
            #line hidden
, 6028), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_flu_time\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_flu_time：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_flu_time\"");

WriteLiteral(" name=\"max_flu_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6277), Tuple.Create("\"", 6306)
            
            #line 117 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 6285), Tuple.Create<System.Object, System.Int32>(Model.max_flu_time
            
            #line default
            #line hidden
, 6285), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">一小时降雨量：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"one_rain\"");

WriteLiteral(" name=\"one_rain\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6481), Tuple.Create("\"", 6506)
            
            #line 120 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 6489), Tuple.Create<System.Object, System.Int32>(Model.one_rain
            
            #line default
            #line hidden
, 6489), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_temper\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">温度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"temper\"");

WriteLiteral(" name=\"temper\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6708), Tuple.Create("\"", 6731)
            
            #line 125 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 6716), Tuple.Create<System.Object, System.Int32>(Model.temper
            
            #line default
            #line hidden
, 6716), false)
);

WriteLiteral(" class=\"easyui-numberbox\"");

WriteLiteral(" min=\"0\"");

WriteLiteral(" max=\"1000\"");

WriteLiteral("  style=\"width:200px;\"");

WriteLiteral("/>\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最高温度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_temper\"");

WriteLiteral(" name=\"max_temper\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6903), Tuple.Create("\"", 6930)
            
            #line 128 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 6911), Tuple.Create<System.Object, System.Int32>(Model.max_temper
            
            #line default
            #line hidden
, 6911), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_temp_time\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最高温度时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_temp_time\"");

WriteLiteral(" name=\"max_temp_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7157), Tuple.Create("\"", 7187)
            
            #line 133 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 7165), Tuple.Create<System.Object, System.Int32>(Model.max_temp_time
            
            #line default
            #line hidden
, 7165), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最低温度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_temper\"");

WriteLiteral(" name=\"min_temper\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7364), Tuple.Create("\"", 7391)
            
            #line 136 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 7372), Tuple.Create<System.Object, System.Int32>(Model.min_temper
            
            #line default
            #line hidden
, 7372), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_min_temp_time\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最低温度时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_temp_time\"");

WriteLiteral(" name=\"min_temp_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7618), Tuple.Create("\"", 7648)
            
            #line 141 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 7626), Tuple.Create<System.Object, System.Int32>(Model.min_temp_time
            
            #line default
            #line hidden
, 7626), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">湿度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"rel_humi\"");

WriteLiteral(" name=\"rel_humi\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7819), Tuple.Create("\"", 7844)
            
            #line 144 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 7827), Tuple.Create<System.Object, System.Int32>(Model.rel_humi
            
            #line default
            #line hidden
, 7827), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"6\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_min_relhumi\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最小湿度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_relhumi\"");

WriteLiteral(" name=\"min_relhumi\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8063), Tuple.Create("\"", 8091)
            
            #line 149 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 8071), Tuple.Create<System.Object, System.Int32>(Model.min_relhumi
            
            #line default
            #line hidden
, 8071), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"6\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最小湿度时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_relhumi_time\"");

WriteLiteral(" name=\"min_relhumi_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8282), Tuple.Create("\"", 8315)
            
            #line 152 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 8290), Tuple.Create<System.Object, System.Int32>(Model.min_relhumi_time
            
            #line default
            #line hidden
, 8290), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_vap_press\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"vap_press\"");

WriteLiteral(" name=\"vap_press\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8524), Tuple.Create("\"", 8550)
            
            #line 157 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 8532), Tuple.Create<System.Object, System.Int32>(Model.vap_press
            
            #line default
            #line hidden
, 8532), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">露点：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"dew_point\"");

WriteLiteral(" name=\"dew_point\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8723), Tuple.Create("\"", 8749)
            
            #line 160 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 8731), Tuple.Create<System.Object, System.Int32>(Model.dew_point
            
            #line default
            #line hidden
, 8731), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_air_press\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">气压：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"air_press\"");

WriteLiteral(" name=\"air_press\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8960), Tuple.Create("\"", 8986)
            
            #line 165 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 8968), Tuple.Create<System.Object, System.Int32>(Model.air_press
            
            #line default
            #line hidden
, 8968), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最大气压：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_press\"");

WriteLiteral(" name=\"max_press\"");

WriteAttribute("value", Tuple.Create(" value=\"", 9161), Tuple.Create("\"", 9187)
            
            #line 168 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 9169), Tuple.Create<System.Object, System.Int32>(Model.max_press
            
            #line default
            #line hidden
, 9169), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_press_time\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最大气压时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_press_time\"");

WriteLiteral(" name=\"max_press_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 9417), Tuple.Create("\"", 9448)
            
            #line 173 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 9425), Tuple.Create<System.Object, System.Int32>(Model.max_press_time
            
            #line default
            #line hidden
, 9425), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最小气压：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_press\"");

WriteLiteral(" name=\"min_press\"");

WriteAttribute("value", Tuple.Create(" value=\"", 9623), Tuple.Create("\"", 9649)
            
            #line 176 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 9631), Tuple.Create<System.Object, System.Int32>(Model.min_press
            
            #line default
            #line hidden
, 9631), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_min_press_time\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最小气压时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_press_time\"");

WriteLiteral(" name=\"min_press_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 9879), Tuple.Create("\"", 9910)
            
            #line 181 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 9887), Tuple.Create<System.Object, System.Int32>(Model.min_press_time
            
            #line default
            #line hidden
, 9887), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">surf_temp：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"surf_temp\"");

WriteLiteral(" name=\"surf_temp\"");

WriteAttribute("value", Tuple.Create(" value=\"", 10090), Tuple.Create("\"", 10116)
            
            #line 184 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 10098), Tuple.Create<System.Object, System.Int32>(Model.surf_temp
            
            #line default
            #line hidden
, 10098), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_surf_temp\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_surf_temp：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_surf_temp\"");

WriteLiteral(" name=\"max_surf_temp\"");

WriteAttribute("value", Tuple.Create(" value=\"", 10350), Tuple.Create("\"", 10380)
            
            #line 189 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 10358), Tuple.Create<System.Object, System.Int32>(Model.max_surf_temp
            
            #line default
            #line hidden
, 10358), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_sutemp_time：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_sutemp_time\"");

WriteLiteral(" name=\"max_sutemp_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 10578), Tuple.Create("\"", 10610)
            
            #line 192 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 10586), Tuple.Create<System.Object, System.Int32>(Model.max_sutemp_time
            
            #line default
            #line hidden
, 10586), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_min_surf_temp\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">min_surf_temp：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_surf_temp\"");

WriteLiteral(" name=\"min_surf_temp\"");

WriteAttribute("value", Tuple.Create(" value=\"", 10844), Tuple.Create("\"", 10874)
            
            #line 197 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 10852), Tuple.Create<System.Object, System.Int32>(Model.min_surf_temp
            
            #line default
            #line hidden
, 10852), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">min_sutemp_time：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_sutemp_time\"");

WriteLiteral(" name=\"min_sutemp_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 11072), Tuple.Create("\"", 11104)
            
            #line 200 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 11080), Tuple.Create<System.Object, System.Int32>(Model.min_sutemp_time
            
            #line default
            #line hidden
, 11080), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 206 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
   Write(RenderPage("~/Areas/zdz/Views/zdzinstantHistory/Extend/Model_FormHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnSubmit\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-ok\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">确定</a>\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        取消\r\n    </a>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/My97DatePicker/WdatePicker.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/Utils.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        jQuery(function() {
            CheckConditions();
function CheckConditions(){
jQuery('fieldset').show(); 
jQuery(""fieldset"").each(function(){ 
if(jQuery('tr',this).length>0){
if(jQuery('tr:visible',this).length>0){jQuery(this).show()} else{jQuery(this).hide()}
}
});
}
;
        });
    </script>
");

WriteLiteral("    ");

            
            #line 234 "..\..\Areas\zdz\Views\zdzinstantHistory\_\Edit.cshtml"
Write(RenderPage("~/Areas/zdz/Views/zdzinstantHistory/Extend/Model_FormJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
