#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/WeiXin/Views/Shared/_Layout.cshtml")]
    public partial class _Areas_WeiXin_Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_WeiXin_Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n    <title>");

            
            #line 6 "..\..\Areas\WeiXin\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - 微信公众平台 小应用 企业号 开放平台 微信支付 JSSDK Senparc.Weixin SDK</title>\r\n    <meta");

WriteLiteral(" name=\"keywords\"");

WriteLiteral(" content=\"微信SDK,微信公众账号,小应用,SDK,微信公众平台,企业号,服务号,订阅号,微信支付,开放平台,Senparc.Weixin,,Senpa" +
"rc.Weixin.MP,JSSDK,开发者,第三方工具,说明,文档,AppStore,微微嗨,盛派网络,Senparc\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"Senparc.Weixin SDK，是目前使用率最高的微信C# SDK，包含完整的公众账号、小应用（应用号）、企业号、开放平台API，帮助第" +
"三方开发者轻松实现微信公众账号和企业号开发。目前包含了Senparc.Weixin.MP（微信公众号SDK）、Senparc.Weixin.QY（微信企业号SD" +
"K）、Senparc.Weixin.Open（微信开放平台SDK），以及微信支付、微信JSSDK的完整SDK和案例。\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/Static/WeiXin/css/reset.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/Static/WeiXin/css/style.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/Resources/JsLib/danktooltip/css/darktooltip.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/danktooltip/js/jquery.darktooltip.min.js\"");

WriteLiteral("></script>\r\n");

WriteLiteral("    ");

            
            #line 14 "..\..\Areas\WeiXin\Views\Shared\_Layout.cshtml"
Write(RenderSection("styles", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n\r\n");

            
            #line 19 "..\..\Areas\WeiXin\Views\Shared\_Layout.cshtml"
        
            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\WeiXin\Views\Shared\_Layout.cshtml"
         if (!IsSectionDefined("catalog"))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"catalog\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" href=\"/WeiXin/Menu/Index\"");

WriteLiteral(">自定义菜单设置工具</a>\r\n                <a");

WriteLiteral(" href=\"/WeiXin/SimulateTool/Index\"");

WriteLiteral(">消息模拟工具</a>\r\n                <a");

WriteLiteral(" href=\"/WeiXin/Cache/Test\"");

WriteLiteral(">缓存测试</a>\r\n            </div>\r\n");

            
            #line 26 "..\..\Areas\WeiXin\Views\Shared\_Layout.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        ");

            
            #line 27 "..\..\Areas\WeiXin\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

WriteLiteral("        ");

            
            #line 29 "..\..\Areas\WeiXin\Views\Shared\_Layout.cshtml"
   Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
