
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的方法，请在此文件的上级目录中的zdzinstantDAL重写(override)该方法。
//     如有问题联系zongeasy@qq.com
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using System.ComponentModel;
using Yamon.Framework.DBUtility;
using System.Collections;
using Yamon.Framework.Common.DataBase;
using Yamon.Framework.Common;
using Yamon.Framework.Common.IO;
using System.IO;
using System.Linq.Expressions;
using Yamon.Framework.DAL;
using Yamon.Module.zdz.Entity;

namespace Yamon.Module.zdz.DAL
{
    /// <summary>
    /// 自动站数据实体类
    ///</summary>
    public partial class _zdzinstantDAL : BaseModelDAL<zdzinstant>
    {
        public _zdzinstantDAL():base("UCenter")
        {
        }





		/// <summary>
		/// 获取分页的数据实体列表
		///</summary>
		/// <param name="totalRows">记录总条数（out）</param>
		/// <param name="nv">页面传递参数集合</param>
		/// <param name="topN">数据条数</param>
		/// <param name="page">页码</param>
		/// <param name="rows">每页记录数</param>
		/// <param name="orderBy">排序</param>
		/// <returns>实体列表</returns>
		public virtual List<zdzinstant> GetEntityListByPage(out int totalRows,int topN = 0, int page=1,int rows=20,string orderBy="")
		{
			string order = "";
			if (!string.IsNullOrEmpty(orderBy))
			{
				order = orderBy;
			}
			object[] searchParams;
			string where = GetSearchSql("", out searchParams);
			string fields="ID,station,sun_rad,aver_rad,max_rad,max_rad_time,uv,aver_uv,max_uv,max_uv_time,instant_vis,ten_aver_vis,two_aver_wd,two_aver_ws,ten_aver_wd,ten_aver_ws,date,ten_max_wd,ten_max_ws,ten_maxws_time,instant_wd,instant_ws,max_flu_wd,max_flu_ws,max_flu_time,one_rain,temper,max_temper,max_temp_time,min_temper,min_temp_time,rel_humi,min_relhumi,min_relhumi_time,vap_press,dew_point,air_press,max_press,max_press_time,min_press,min_press_time,surf_temp,max_surf_temp,max_sutemp_time,min_surf_temp,min_sutemp_time";
			return GetEntityListByPage("1=1 "+ where, searchParams,order,fields, rows,page,topN,out totalRows);
		}

		/// <summary>
		/// 获取分页的数据列表DataTable
		///</summary>
		/// <param name="totalRows">记录总条数（out）</param>
		/// <param name="nv">页面传递参数集合</param>
		/// <param name="topN">数据条数</param>
		/// <param name="page">页码</param>
		/// <param name="rows">每页记录数</param>
		/// <param name="orderBy">排序</param>
		/// <returns>DataTable</returns>
		public virtual DataTable GetEntityTableByPage(out int totalRows,int topN = 0, int page=1,int rows=20,string orderBy="")
		{
			string order = "";
			if (!string.IsNullOrEmpty(orderBy))
			{
				order = orderBy;
			}
			object[] searchParams;
			string where = GetSearchSql("", out searchParams);
			string fields="ID,station,sun_rad,aver_rad,max_rad,max_rad_time,uv,aver_uv,max_uv,max_uv_time,instant_vis,ten_aver_vis,two_aver_wd,two_aver_ws,ten_aver_wd,ten_aver_ws,date,ten_max_wd,ten_max_ws,ten_maxws_time,instant_wd,instant_ws,max_flu_wd,max_flu_ws,max_flu_time,one_rain,temper,max_temper,max_temp_time,min_temper,min_temp_time,rel_humi,min_relhumi,min_relhumi_time,vap_press,dew_point,air_press,max_press,max_press_time,min_press,min_press_time,surf_temp,max_surf_temp,max_sutemp_time,min_surf_temp,min_sutemp_time";
			return GetEntityTableByPage("1=1 "+ where, searchParams,order,fields,rows,page,topN,out totalRows);
		}

		/// <summary>
        /// 拼接查询Sql语句及参数
        /// </summary>
        /// <param name="nv">页面传递的参数集合</param>
        /// <param name="notIn">排除字段</param>
        /// <param name="arrParam">out查询参数</param>
        /// <returns>查询Sql语句</returns>
		public virtual string GetSearchSql(string notIn,out object[] arrParam)
		{
			StringBuilder sb=new StringBuilder();
			string value="";
			string value1 = "";
			string value2 = "";
			ArrayList param=new ArrayList();
			
			
			//date
			if (!("," + notIn.ToLower() + ",").Contains(",date,"))
			{
					 value1 = RequestHelper.GetString("date_Start");
					 value2 = RequestHelper.GetString("date_End");
			    if (!string.IsNullOrEmpty(value1))
			    {
			      sb.Append(" AND [`date`] >=?");
			      param.Add(value1);
			    }
			    if (!string.IsNullOrEmpty(value2))
			    {
			      sb.Append(" AND [`date`] <=?");
			      param.Add(value2);
			    }
			}
			
			
			//station
			if (!("," + notIn.ToLower() + ",").Contains(",station,"))
			{
				value = RequestHelper.GetString("station");
				if (!string.IsNullOrEmpty(value))
				{
				 sb.Append(" AND [`station`]=?");
				  param.Add(value);
				}
			}
			
			
			//instant_vis
			if (!("," + notIn.ToLower() + ",").Contains(",instant_vis,"))
			{
			value = RequestHelper.GetString("instant_vis");
			if (!string.IsNullOrEmpty(value))
			{
			    string[] arrValue = value.Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
			    if (arrValue.Length > 1)
			    {
			        for (int i = 0; i < arrValue.Length; i++)
			        {
			       		sb.Append(" AND [`instant_vis`] like ?");
			       		param.Add("%"+ arrValue[i]+"%");
			        }
			    }
			    else
			    {
			          sb.Append(" AND [`instant_vis`] like ?");
			          param.Add("%"+ value+"%");
			    }
			}
			}
			
			
			//instant_wd
			if (!("," + notIn.ToLower() + ",").Contains(",instant_wd,"))
			{
				value1 = RequestHelper.GetString("instant_wd_Start");
				value2 = RequestHelper.GetString("instant_wd_End");
				value =RequestHelper.GetString("instant_wd");
				if (!string.IsNullOrEmpty(value) && string.IsNullOrEmpty(value1) && string.IsNullOrEmpty(value2))
				{
				  sb.Append(" AND [`instant_wd`] =?");
				  param.Add(value);
				}
				if (!string.IsNullOrEmpty(value1))
				{
				  sb.Append(" AND [`instant_wd`] >=?");
				  param.Add(value1);
				}
				if (!string.IsNullOrEmpty(value2))
				{
				  sb.Append(" AND [`instant_wd`] <=?");
				  param.Add(value2);
				}
			}
			
			
			//instant_ws
			if (!("," + notIn.ToLower() + ",").Contains(",instant_ws,"))
			{
				value1 = RequestHelper.GetString("instant_ws_Start");
				value2 = RequestHelper.GetString("instant_ws_End");
				value =RequestHelper.GetString("instant_ws");
				if (!string.IsNullOrEmpty(value) && string.IsNullOrEmpty(value1) && string.IsNullOrEmpty(value2))
				{
				  sb.Append(" AND [`instant_ws`] =?");
				  param.Add(value);
				}
				if (!string.IsNullOrEmpty(value1))
				{
				  sb.Append(" AND [`instant_ws`] >=?");
				  param.Add(value1);
				}
				if (!string.IsNullOrEmpty(value2))
				{
				  sb.Append(" AND [`instant_ws`] <=?");
				  param.Add(value2);
				}
			}
			
			
			//one_rain
			if (!("," + notIn.ToLower() + ",").Contains(",one_rain,"))
			{
				value = RequestHelper.GetString("one_rain");
				if (!string.IsNullOrEmpty(value))
				{
				 sb.Append(" AND [`one_rain`]=?");
				  param.Add(value);
				}
			}
			
			
			//temper
			if (!("," + notIn.ToLower() + ",").Contains(",temper,"))
			{
				value1 = RequestHelper.GetString("temper_Start");
				value2 = RequestHelper.GetString("temper_End");
				value =RequestHelper.GetString("temper");
				if (!string.IsNullOrEmpty(value) && string.IsNullOrEmpty(value1) && string.IsNullOrEmpty(value2))
				{
				  sb.Append(" AND [`temper`] =?");
				  param.Add(value);
				}
				if (!string.IsNullOrEmpty(value1))
				{
				  sb.Append(" AND [`temper`] >=?");
				  param.Add(value1);
				}
				if (!string.IsNullOrEmpty(value2))
				{
				  sb.Append(" AND [`temper`] <=?");
				  param.Add(value2);
				}
			}
			arrParam=param.ToArray();
			return sb.ToString();

		}

		
	    public virtual zdzinstant GetModelValue(zdzinstant model)
        {
            return model;
        }
		/// <summary>
        /// 设置自动站数据实体(zdzinstant)的显示值
        /// </summary>
        /// <param name="model">自动站数据实体(zdzinstant)</param>
        /// <returns>自动站数据实体(zdzinstant)</returns>
		public virtual zdzinstant GetModelShowValue(zdzinstant model,bool clearValue=false)
        {
            model=GetModelValue(model);
			if(clearValue)
			{
			}
			return model;
		}
		
		/// <summary>
        /// 设置自动站数据实体(zdzinstant)的列表显示值
        /// </summary>
        /// <param name="model">自动站数据实体(zdzinstant)</param>
        /// <returns>自动站数据实体(zdzinstant)</returns>
		public virtual zdzinstant GetModelGridShowValue(zdzinstant model){
			model=GetModelShowValue(model);
			return model;
        }

        public virtual zdzinstant GetInfoByID(object id){
            zdzinstant model = GetModelByID(id);
            model = GetModelShowValue(model);
            return model;
        } 


      #region 新建相关方法
		/// <summary>
        /// 设置新增入库时自动站数据实体(zdzinstant)默认值
        /// </summary>
        /// <param name="model">自动站数据实体(zdzinstant)</param>
        /// <returns>自动站数据实体(zdzinstant)</returns>
		public virtual zdzinstant GetInsertModelValue(zdzinstant model)
		{
			model.ID =null;
			return model;
		}		/// <summary>
        /// 设置新建页面的自动站数据实体(zdzinstant)默认值
        /// </summary>
        /// <param name="model">自动站数据实体(zdzinstant)</param>
        /// <returns>自动站数据实体(zdzinstant)</returns>
		public virtual zdzinstant GetCreateFormDefaultValue()
		{
            zdzinstant model = new zdzinstant();
            return model;
		}

		/// <summary>
        /// 新建数据格式验证
        /// </summary>
        /// <param name="model">自动站数据实体(zdzinstant)</param>
        public virtual void CreateFormValidator(zdzinstant model)
        {
			string value="";
}
      #endregion

      #region 修改相关方法
		/// <summary>
        /// 设置更新入库时自动站数据实体(zdzinstant)默认值
        /// </summary>
        /// <param name="model">自动站数据实体(zdzinstant)</param>
        /// <returns>自动站数据实体(zdzinstant)</returns>
		public virtual zdzinstant GetUpdateModelValue(zdzinstant model)
		{
			return model;
		}		/// <summary>
        /// 设置编辑页面的自动站数据实体(zdzinstant)默认值
        /// </summary>
        /// <param name="model">自动站数据实体(zdzinstant)</param>
        /// <returns>自动站数据实体(zdzinstant)</returns>
		public virtual zdzinstant GetEditFormDefaultValue(zdzinstant model)
		{
			return model;
		}

		/// <summary>
        /// 编辑数据格式验证
        /// </summary>
        /// <param name="model">自动站数据实体(zdzinstant)</param>
        public virtual void EditFormValidator(zdzinstant model)
        {
			string value="";
}
      #endregion

    }
}
