#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage.Entity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/zdz/Views/zdzinstant/_/Create.cshtml")]
    public partial class _Areas_zdz_Views_zdzinstant___Create_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_zdz_Views_zdzinstant___Create_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------
    ViewBag.Title="新建自动站数据";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #F6F6F6; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/zdz/zdzinstant/Create\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_ID\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">编号：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ID\"");

WriteLiteral(" name=\"ID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 813), Tuple.Create("\"", 832)
            
            #line 22 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 821), Tuple.Create<System.Object, System.Int32>(Model.ID
            
            #line default
            #line hidden
, 821), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">站名：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"station\"");

WriteLiteral(" name=\"station\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1018), Tuple.Create("\"", 1042)
            
            #line 25 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1026), Tuple.Create<System.Object, System.Int32>(Model.station
            
            #line default
            #line hidden
, 1026), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_sun_rad\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">太阳辐射：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"sun_rad\"");

WriteLiteral(" name=\"sun_rad\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1250), Tuple.Create("\"", 1274)
            
            #line 30 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1258), Tuple.Create<System.Object, System.Int32>(Model.sun_rad
            
            #line default
            #line hidden
, 1258), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">平均太阳辐射：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"aver_rad\"");

WriteLiteral(" name=\"aver_rad\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1449), Tuple.Create("\"", 1474)
            
            #line 33 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1457), Tuple.Create<System.Object, System.Int32>(Model.aver_rad
            
            #line default
            #line hidden
, 1457), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_rad\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最高太阳辐射：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_rad\"");

WriteLiteral(" name=\"max_rad\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1683), Tuple.Create("\"", 1707)
            
            #line 38 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1691), Tuple.Create<System.Object, System.Int32>(Model.max_rad
            
            #line default
            #line hidden
, 1691), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最高太阳辐射时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_rad_time\"");

WriteLiteral(" name=\"max_rad_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1892), Tuple.Create("\"", 1921)
            
            #line 41 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1900), Tuple.Create<System.Object, System.Int32>(Model.max_rad_time
            
            #line default
            #line hidden
, 1900), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_uv\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">uv：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"uv\"");

WriteLiteral(" name=\"uv\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2111), Tuple.Create("\"", 2130)
            
            #line 46 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2119), Tuple.Create<System.Object, System.Int32>(Model.uv
            
            #line default
            #line hidden
, 2119), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">aver_uv：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"aver_uv\"");

WriteLiteral(" name=\"aver_uv\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2304), Tuple.Create("\"", 2328)
            
            #line 49 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2312), Tuple.Create<System.Object, System.Int32>(Model.aver_uv
            
            #line default
            #line hidden
, 2312), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_uv\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_uv：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_uv\"");

WriteLiteral(" name=\"max_uv\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2534), Tuple.Create("\"", 2557)
            
            #line 54 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2542), Tuple.Create<System.Object, System.Int32>(Model.max_uv
            
            #line default
            #line hidden
, 2542), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_uv_time：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_uv_time\"");

WriteLiteral(" name=\"max_uv_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2743), Tuple.Create("\"", 2771)
            
            #line 57 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2751), Tuple.Create<System.Object, System.Int32>(Model.max_uv_time
            
            #line default
            #line hidden
, 2751), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_instant_vis\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">能见度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"instant_vis\"");

WriteLiteral(" name=\"instant_vis\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2989), Tuple.Create("\"", 3017)
            
            #line 62 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2997), Tuple.Create<System.Object, System.Int32>(Model.instant_vis
            
            #line default
            #line hidden
, 2997), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"9\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">十分钟平均能见度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ten_aver_vis\"");

WriteLiteral(" name=\"ten_aver_vis\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3202), Tuple.Create("\"", 3231)
            
            #line 65 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3210), Tuple.Create<System.Object, System.Int32>(Model.ten_aver_vis
            
            #line default
            #line hidden
, 3210), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"9\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_two_aver_wd\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">两分钟平均风向：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"two_aver_wd\"");

WriteLiteral(" name=\"two_aver_wd\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3453), Tuple.Create("\"", 3481)
            
            #line 70 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3461), Tuple.Create<System.Object, System.Int32>(Model.two_aver_wd
            
            #line default
            #line hidden
, 3461), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"6\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">两分钟平均风力：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"two_aver_ws\"");

WriteLiteral(" name=\"two_aver_ws\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3663), Tuple.Create("\"", 3691)
            
            #line 73 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3671), Tuple.Create<System.Object, System.Int32>(Model.two_aver_ws
            
            #line default
            #line hidden
, 3671), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_ten_aver_wd\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">十分钟平均风向：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ten_aver_wd\"");

WriteLiteral(" name=\"ten_aver_wd\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3913), Tuple.Create("\"", 3941)
            
            #line 78 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3921), Tuple.Create<System.Object, System.Int32>(Model.ten_aver_wd
            
            #line default
            #line hidden
, 3921), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"6\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">十分钟平均风力：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ten_aver_ws\"");

WriteLiteral(" name=\"ten_aver_ws\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4123), Tuple.Create("\"", 4151)
            
            #line 81 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 4131), Tuple.Create<System.Object, System.Int32>(Model.ten_aver_ws
            
            #line default
            #line hidden
, 4131), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_date\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">数据时次：</td><td>&nbsp;    <input");

WriteLiteral(" class=\"Wdate\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" onClick=\"WdatePicker({dateFmt:\'yyyy-MM-dd HH:mm:ss\'})\"");

WriteLiteral(" id=\"date\"");

WriteLiteral(" name=\"date\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4420), Tuple.Create("\"", 4493)
            
            #line 85 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
                                                                                  , Tuple.Create(Tuple.Create("", 4428), Tuple.Create<System.Object, System.Int32>(Model.date==null?"":Model.date.ToString("yyyy-MM-dd HH:mm:ss")
            
            #line default
            #line hidden
, 4428), false)
);

WriteLiteral(" style=\"width:135px;\"");

WriteLiteral(">\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">十分钟最大风向：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ten_max_wd\"");

WriteLiteral(" name=\"ten_max_wd\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4622), Tuple.Create("\"", 4649)
            
            #line 88 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 4630), Tuple.Create<System.Object, System.Int32>(Model.ten_max_wd
            
            #line default
            #line hidden
, 4630), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"6\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_ten_max_ws\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">十分钟最大风力：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ten_max_ws\"");

WriteLiteral(" name=\"ten_max_ws\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4868), Tuple.Create("\"", 4895)
            
            #line 93 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 4876), Tuple.Create<System.Object, System.Int32>(Model.ten_max_ws
            
            #line default
            #line hidden
, 4876), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">十分钟最大风力时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ten_maxws_time\"");

WriteLiteral(" name=\"ten_maxws_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5085), Tuple.Create("\"", 5116)
            
            #line 96 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 5093), Tuple.Create<System.Object, System.Int32>(Model.ten_maxws_time
            
            #line default
            #line hidden
, 5093), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_instant_wd\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">瞬时风向：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"instant_wd\"");

WriteLiteral(" name=\"instant_wd\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5332), Tuple.Create("\"", 5359)
            
            #line 101 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 5340), Tuple.Create<System.Object, System.Int32>(Model.instant_wd
            
            #line default
            #line hidden
, 5340), false)
);

WriteLiteral(" class=\"easyui-numberbox\"");

WriteLiteral(" min=\"0\"");

WriteLiteral(" max=\"1000\"");

WriteLiteral("  precision=\"0\"");

WriteLiteral(" style=\"width:200px;\"");

WriteLiteral("/>\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">瞬时风力：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"instant_ws\"");

WriteLiteral(" name=\"instant_ws\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5545), Tuple.Create("\"", 5572)
            
            #line 104 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 5553), Tuple.Create<System.Object, System.Int32>(Model.instant_ws
            
            #line default
            #line hidden
, 5553), false)
);

WriteLiteral(" class=\"easyui-numberbox\"");

WriteLiteral(" min=\"0\"");

WriteLiteral(" max=\"1000\"");

WriteLiteral("  precision=\"1\"");

WriteLiteral(" style=\"width:200px;\"");

WriteLiteral("/>\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_flu_wd\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_flu_wd：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_flu_wd\"");

WriteLiteral(" name=\"max_flu_wd\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5803), Tuple.Create("\"", 5830)
            
            #line 109 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 5811), Tuple.Create<System.Object, System.Int32>(Model.max_flu_wd
            
            #line default
            #line hidden
, 5811), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"6\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_flu_ws：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_flu_ws\"");

WriteLiteral(" name=\"max_flu_ws\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6013), Tuple.Create("\"", 6040)
            
            #line 112 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 6021), Tuple.Create<System.Object, System.Int32>(Model.max_flu_ws
            
            #line default
            #line hidden
, 6021), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_flu_time\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_flu_time：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_flu_time\"");

WriteLiteral(" name=\"max_flu_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6270), Tuple.Create("\"", 6299)
            
            #line 117 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 6278), Tuple.Create<System.Object, System.Int32>(Model.max_flu_time
            
            #line default
            #line hidden
, 6278), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">一小时降雨量：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"one_rain\"");

WriteLiteral(" name=\"one_rain\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6474), Tuple.Create("\"", 6499)
            
            #line 120 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 6482), Tuple.Create<System.Object, System.Int32>(Model.one_rain
            
            #line default
            #line hidden
, 6482), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_temper\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">温度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"temper\"");

WriteLiteral(" name=\"temper\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6701), Tuple.Create("\"", 6724)
            
            #line 125 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 6709), Tuple.Create<System.Object, System.Int32>(Model.temper
            
            #line default
            #line hidden
, 6709), false)
);

WriteLiteral(" class=\"easyui-numberbox\"");

WriteLiteral(" min=\"0\"");

WriteLiteral(" max=\"1000\"");

WriteLiteral("  style=\"width:200px;\"");

WriteLiteral("/>\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最高温度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_temper\"");

WriteLiteral(" name=\"max_temper\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6896), Tuple.Create("\"", 6923)
            
            #line 128 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 6904), Tuple.Create<System.Object, System.Int32>(Model.max_temper
            
            #line default
            #line hidden
, 6904), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_temp_time\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最高温度时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_temp_time\"");

WriteLiteral(" name=\"max_temp_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7150), Tuple.Create("\"", 7180)
            
            #line 133 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 7158), Tuple.Create<System.Object, System.Int32>(Model.max_temp_time
            
            #line default
            #line hidden
, 7158), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最低温度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_temper\"");

WriteLiteral(" name=\"min_temper\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7357), Tuple.Create("\"", 7384)
            
            #line 136 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 7365), Tuple.Create<System.Object, System.Int32>(Model.min_temper
            
            #line default
            #line hidden
, 7365), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_min_temp_time\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最低温度时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_temp_time\"");

WriteLiteral(" name=\"min_temp_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7611), Tuple.Create("\"", 7641)
            
            #line 141 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 7619), Tuple.Create<System.Object, System.Int32>(Model.min_temp_time
            
            #line default
            #line hidden
, 7619), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">湿度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"rel_humi\"");

WriteLiteral(" name=\"rel_humi\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7812), Tuple.Create("\"", 7837)
            
            #line 144 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 7820), Tuple.Create<System.Object, System.Int32>(Model.rel_humi
            
            #line default
            #line hidden
, 7820), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"6\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_min_relhumi\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最小湿度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_relhumi\"");

WriteLiteral(" name=\"min_relhumi\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8056), Tuple.Create("\"", 8084)
            
            #line 149 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 8064), Tuple.Create<System.Object, System.Int32>(Model.min_relhumi
            
            #line default
            #line hidden
, 8064), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"6\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最小湿度时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_relhumi_time\"");

WriteLiteral(" name=\"min_relhumi_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8275), Tuple.Create("\"", 8308)
            
            #line 152 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 8283), Tuple.Create<System.Object, System.Int32>(Model.min_relhumi_time
            
            #line default
            #line hidden
, 8283), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_vap_press\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"vap_press\"");

WriteLiteral(" name=\"vap_press\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8517), Tuple.Create("\"", 8543)
            
            #line 157 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 8525), Tuple.Create<System.Object, System.Int32>(Model.vap_press
            
            #line default
            #line hidden
, 8525), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">露点：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"dew_point\"");

WriteLiteral(" name=\"dew_point\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8716), Tuple.Create("\"", 8742)
            
            #line 160 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 8724), Tuple.Create<System.Object, System.Int32>(Model.dew_point
            
            #line default
            #line hidden
, 8724), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_air_press\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">气压：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"air_press\"");

WriteLiteral(" name=\"air_press\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8953), Tuple.Create("\"", 8979)
            
            #line 165 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 8961), Tuple.Create<System.Object, System.Int32>(Model.air_press
            
            #line default
            #line hidden
, 8961), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最大气压：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_press\"");

WriteLiteral(" name=\"max_press\"");

WriteAttribute("value", Tuple.Create(" value=\"", 9154), Tuple.Create("\"", 9180)
            
            #line 168 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 9162), Tuple.Create<System.Object, System.Int32>(Model.max_press
            
            #line default
            #line hidden
, 9162), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_press_time\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最大气压时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_press_time\"");

WriteLiteral(" name=\"max_press_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 9410), Tuple.Create("\"", 9441)
            
            #line 173 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 9418), Tuple.Create<System.Object, System.Int32>(Model.max_press_time
            
            #line default
            #line hidden
, 9418), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最小气压：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_press\"");

WriteLiteral(" name=\"min_press\"");

WriteAttribute("value", Tuple.Create(" value=\"", 9616), Tuple.Create("\"", 9642)
            
            #line 176 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 9624), Tuple.Create<System.Object, System.Int32>(Model.min_press
            
            #line default
            #line hidden
, 9624), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_min_press_time\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最小气压时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_press_time\"");

WriteLiteral(" name=\"min_press_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 9872), Tuple.Create("\"", 9903)
            
            #line 181 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 9880), Tuple.Create<System.Object, System.Int32>(Model.min_press_time
            
            #line default
            #line hidden
, 9880), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">surf_temp：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"surf_temp\"");

WriteLiteral(" name=\"surf_temp\"");

WriteAttribute("value", Tuple.Create(" value=\"", 10083), Tuple.Create("\"", 10109)
            
            #line 184 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 10091), Tuple.Create<System.Object, System.Int32>(Model.surf_temp
            
            #line default
            #line hidden
, 10091), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_max_surf_temp\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_surf_temp：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_surf_temp\"");

WriteLiteral(" name=\"max_surf_temp\"");

WriteAttribute("value", Tuple.Create(" value=\"", 10343), Tuple.Create("\"", 10373)
            
            #line 189 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 10351), Tuple.Create<System.Object, System.Int32>(Model.max_surf_temp
            
            #line default
            #line hidden
, 10351), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">max_sutemp_time：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"max_sutemp_time\"");

WriteLiteral(" name=\"max_sutemp_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 10571), Tuple.Create("\"", 10603)
            
            #line 192 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 10579), Tuple.Create<System.Object, System.Int32>(Model.max_sutemp_time
            
            #line default
            #line hidden
, 10579), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_min_surf_temp\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">min_surf_temp：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_surf_temp\"");

WriteLiteral(" name=\"min_surf_temp\"");

WriteAttribute("value", Tuple.Create(" value=\"", 10837), Tuple.Create("\"", 10867)
            
            #line 197 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 10845), Tuple.Create<System.Object, System.Int32>(Model.min_surf_temp
            
            #line default
            #line hidden
, 10845), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">min_sutemp_time：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"min_sutemp_time\"");

WriteLiteral(" name=\"min_sutemp_time\"");

WriteAttribute("value", Tuple.Create(" value=\"", 11065), Tuple.Create("\"", 11097)
            
            #line 200 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 11073), Tuple.Create<System.Object, System.Int32>(Model.min_sutemp_time
            
            #line default
            #line hidden
, 11073), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"0\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 206 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
   Write(RenderPage("~/Areas/zdz/Views/zdzinstant/Extend/Model_FormHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnSubmit\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-ok\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">确定</a>\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        取消\r\n    </a>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/My97DatePicker/WdatePicker.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/Utils.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        jQuery(function() {
            CheckConditions();
function CheckConditions(){
jQuery('fieldset').show(); 
jQuery(""fieldset"").each(function(){ 
if(jQuery('tr',this).length>0){
if(jQuery('tr:visible',this).length>0){jQuery(this).show()} else{jQuery(this).hide()}
}
});
}
;
        });
    </script>
");

WriteLiteral("    ");

            
            #line 234 "..\..\Areas\zdz\Views\zdzinstant\_\Create.cshtml"
Write(RenderPage("~/Areas/zdz/Views/zdzinstant/Extend/Model_FormJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
