#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage.Entity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Weather/Views/WeatherNodes/_/Edit.cshtml")]
    public partial class _Areas_Weather_Views_WeatherNodes___Edit_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Weather_Views_WeatherNodes___Edit_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------
    ViewBag.Title="编辑节点";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #FFFFFF; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/Weather/WeatherNodes/Edit\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_ParentID\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_ParentID\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">所属栏目：</td><td>&nbsp;\r\n\r\n<input");

WriteLiteral(" id=\"ParentID\"");

WriteLiteral(" name=\"ParentID\"");

WriteAttribute("url", Tuple.Create(" url=\"", 842), Tuple.Create("\"", 917)
, Tuple.Create(Tuple.Create("", 848), Tuple.Create("/api/Weather/WeatherNodes/EditTree?&iscombo=1&Value=", 848), true)
            
            #line 22 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
                , Tuple.Create(Tuple.Create("", 900), Tuple.Create<System.Object, System.Int32>(Model.ParentID
            
            #line default
            #line hidden
, 900), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 918), Tuple.Create("\"", 943)
            
            #line 22 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
                                          , Tuple.Create(Tuple.Create("", 926), Tuple.Create<System.Object, System.Int32>(Model.ParentID
            
            #line default
            #line hidden
, 926), false)
);

WriteLiteral(" style=\"width: 200px\"");

WriteLiteral(" required=\"true\"");

WriteLiteral(" />\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var ParentID_Value = \'");

            
            #line 24 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
                      Write(Model.ParentID);

            
            #line default
            #line hidden
WriteLiteral(@"';
    jQuery(function() {
        jQuery('#ParentID').combotree(
        {
            onLoadSuccess:function(node, data) {
                jQuery('#ParentID').combotree('setValue',ParentID_Value);
            }
        });
    });
</script>
</td></tr>
<tr");

WriteLiteral(" id=\"Container_NodeName\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_NodeName\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">栏目名称：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"NodeName\"");

WriteLiteral(" name=\"NodeName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1465), Tuple.Create("\"", 1490)
            
            #line 36 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1473), Tuple.Create<System.Object, System.Int32>(Model.NodeName
            
            #line default
            #line hidden
, 1473), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"50\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_NodeType\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_NodeType\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">栏目类型：</td><td>&nbsp;\r\n<select");

WriteLiteral(" id=\"NodeType\"");

WriteLiteral(" class=\"easyui-combobox\"");

WriteLiteral(" name=\"NodeType\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(">\r\n<option");

WriteLiteral(" value=\"\"");

WriteLiteral(">请选择</option>\r\n");

            
            #line 41 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowSelectOptions(ViewBag.DAL.NameValue_NodeType, Model.NodeType)));

            
            #line default
            #line hidden
WriteLiteral("\r\n</select></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_NodePicUrl\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_NodePicUrl\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">图标：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"NodePicUrl\"");

WriteLiteral(" name=\"NodePicUrl\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2041), Tuple.Create("\"", 2068)
            
            #line 44 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2049), Tuple.Create<System.Object, System.Int32>(Model.NodePicUrl
            
            #line default
            #line hidden
, 2049), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_TemplateName\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_TemplateName\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">模板路径：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"TemplateName\"");

WriteLiteral(" name=\"TemplateName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2311), Tuple.Create("\"", 2340)
            
            #line 47 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2319), Tuple.Create<System.Object, System.Int32>(Model.TemplateName
            
            #line default
            #line hidden
, 2319), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"500\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Tips\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Tips\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">节点提示：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Tips\"");

WriteLiteral(" name=\"Tips\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2552), Tuple.Create("\"", 2573)
            
            #line 50 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2560), Tuple.Create<System.Object, System.Int32>(Model.Tips
            
            #line default
            #line hidden
, 2560), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"255\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Description\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Description\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">节点说明：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Description\"");

WriteLiteral(" name=\"Description\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2813), Tuple.Create("\"", 2841)
            
            #line 53 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2821), Tuple.Create<System.Object, System.Int32>(Model.Description
            
            #line default
            #line hidden
, 2821), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"16\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_SourceDepartment\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_SourceDepartment\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">来源部门：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"SourceDepartment\"");

WriteLiteral(" name=\"SourceDepartment\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3100), Tuple.Create("\"", 3133)
            
            #line 56 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 3108), Tuple.Create<System.Object, System.Int32>(Model.SourceDepartment
            
            #line default
            #line hidden
, 3108), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_ConcactName\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_ConcactName\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">联系人：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ConcactName\"");

WriteLiteral(" name=\"ConcactName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3371), Tuple.Create("\"", 3399)
            
            #line 59 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 3379), Tuple.Create<System.Object, System.Int32>(Model.ConcactName
            
            #line default
            #line hidden
, 3379), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"500\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_DataSourceType\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_DataSourceType\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">数据来源：</td><td>&nbsp;\r\n");

            
            #line 62 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_DataSourceType, "DataSourceType", Model.DataSourceType, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_DataApiUrl\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_DataApiUrl\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">数据接口地址：</td><td>&nbsp;\r\n<textarea");

WriteLiteral(" id=\"DataApiUrl\"");

WriteLiteral(" name=\"DataApiUrl\"");

WriteLiteral(" class=\"easyui-validatebox\"");

WriteLiteral("  style=\"width:500px;height:80px\"");

WriteLiteral(">");

            
            #line 65 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
                                                                                                    Write(Model.DataApiUrl);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_isDataAccess\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_isDataAccess\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">是否接入：</td><td>&nbsp;\r\n\r\n");

            
            #line 69 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_isDataAccess, "isDataAccess", Model.isDataAccess, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n<span");

WriteLiteral(" class=\"tips\"");

WriteLiteral(">（数据是否正常接入）</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_OrderID\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_OrderID\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">排序号：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"OrderID\"");

WriteLiteral(" name=\"OrderID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4382), Tuple.Create("\"", 4406)
            
            #line 72 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 4390), Tuple.Create<System.Object, System.Int32>(Model.OrderID
            
            #line default
            #line hidden
, 4390), false)
);

WriteLiteral(" class=\"easyui-numberbox\"");

WriteLiteral(" min=\"0\"");

WriteLiteral(" max=\"10000\"");

WriteLiteral("  style=\"width:200px;\"");

WriteLiteral("/>\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_IsImportToDB\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_IsImportToDB\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">录入方式：</td><td>&nbsp;\r\n");

            
            #line 75 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_IsImportToDB, "IsImportToDB", Model.IsImportToDB, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_IsTiming\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_IsTiming\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">是否定时：</td><td>&nbsp;\r\n\r\n");

            
            #line 79 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_IsTiming, "IsTiming", Model.IsTiming, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_SubPlanDesc\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_SubPlanDesc\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">周期描述：</td><td>&nbsp;\r\n<textarea");

WriteLiteral(" id=\"SubPlanDesc\"");

WriteLiteral(" name=\"SubPlanDesc\"");

WriteLiteral(" class=\"easyui-validatebox\"");

WriteLiteral("  style=\"width:400px;height:40px\"");

WriteLiteral(">");

            
            #line 82 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
                                                                                                      Write(Model.SubPlanDesc);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_NodePath\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_NodePath\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">路径规则：</td><td>&nbsp;\r\n<textarea");

WriteLiteral(" id=\"NodePath\"");

WriteLiteral(" name=\"NodePath\"");

WriteLiteral(" class=\"easyui-validatebox\"");

WriteLiteral("  style=\"width:500px;height:50px\"");

WriteLiteral(">");

            
            #line 85 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
                                                                                                Write(Model.NodePath);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n<span");

WriteLiteral(" class=\"tips\"");

WriteLiteral(">路径规则</span><span");

WriteLiteral(" title=\"路径规则\"");

WriteLiteral("  class=\"easyui-tooltip\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" data-options=\"plain:true,iconCls:\'icon-help\'\"");

WriteLiteral("></a></span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Deley\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Deley\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">延时分钟：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Deley\"");

WriteLiteral(" name=\"Deley\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5713), Tuple.Create("\"", 5735)
            
            #line 88 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5721), Tuple.Create<System.Object, System.Int32>(Model.Deley
            
            #line default
            #line hidden
, 5721), false)
);

WriteLiteral(" class=\"easyui-numberbox\"");

WriteLiteral(" min=\"0\"");

WriteLiteral(" max=\"1000\"");

WriteLiteral("  style=\"width:200px;\"");

WriteLiteral("/>\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_DateTimeFormat\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_DateTimeFormat\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">文件名日期格式：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"DateTimeFormat\"");

WriteLiteral(" name=\"DateTimeFormat\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5983), Tuple.Create("\"", 6014)
            
            #line 91 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5991), Tuple.Create<System.Object, System.Int32>(Model.DateTimeFormat
            
            #line default
            #line hidden
, 5991), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n<span");

WriteLiteral(" class=\"tips\"");

WriteLiteral(">yyyyMMddHHmm</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_NameRule\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_NameRule\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">入库命名规则：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"NameRule\"");

WriteLiteral(" name=\"NameRule\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6281), Tuple.Create("\"", 6306)
            
            #line 94 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 6289), Tuple.Create<System.Object, System.Int32>(Model.NameRule
            
            #line default
            #line hidden
, 6289), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"200\"");

WriteLiteral(" style=\"width:400px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_NamePrefix\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_NamePrefix\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">命名规则前辍：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"NamePrefix\"");

WriteLiteral(" name=\"NamePrefix\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6544), Tuple.Create("\"", 6571)
            
            #line 97 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 6552), Tuple.Create<System.Object, System.Int32>(Model.NamePrefix
            
            #line default
            #line hidden
, 6552), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"100\"");

WriteLiteral(" style=\"width:400px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_IsMonitor\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_IsMonitor\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">是否加入监控：</td><td>&nbsp;\r\n\r\n");

            
            #line 101 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_IsMonitor, "IsMonitor", Model.IsMonitor, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_IsRename\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_IsRename\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">是否重命名：</td><td>&nbsp;\r\n\r\n");

            
            #line 105 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_IsRename, "IsRename", Model.IsRename, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_OpenType\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_OpenType\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">打开方式：</td><td>&nbsp;\r\n");

            
            #line 108 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_OpenType, "OpenType", Model.OpenType, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_LinkUrl\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_LinkUrl\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">外部链接地址：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"LinkUrl\"");

WriteLiteral(" name=\"LinkUrl\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7451), Tuple.Create("\"", 7475)
            
            #line 111 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 7459), Tuple.Create<System.Object, System.Int32>(Model.LinkUrl
            
            #line default
            #line hidden
, 7459), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"255\"");

WriteLiteral(" style=\"width:400px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_RunHttpTask\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_RunHttpTask\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">执行网页任务：</td><td>&nbsp;\r\n<textarea");

WriteLiteral(" id=\"RunHttpTask\"");

WriteLiteral(" name=\"RunHttpTask\"");

WriteLiteral(" class=\"easyui-validatebox\"");

WriteLiteral("  style=\"width:500px;height:80px\"");

WriteLiteral(">");

            
            #line 114 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
                                                                                                      Write(Model.RunHttpTask);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n<span");

WriteLiteral(" class=\"tips\"");

WriteLiteral(">输入Url地址，每行一个</span></td></tr>\r\n<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"NodeID\"");

WriteLiteral("  name=\"NodeID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7899), Tuple.Create("\"", 7922)
            
            #line 116 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 7907), Tuple.Create<System.Object, System.Int32>(Model.NodeID
            
            #line default
            #line hidden
, 7907), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"channel\"");

WriteLiteral("  name=\"channel\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7974), Tuple.Create("\"", 7998)
            
            #line 116 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
                                                   , Tuple.Create(Tuple.Create("", 7982), Tuple.Create<System.Object, System.Int32>(Model.channel
            
            #line default
            #line hidden
, 7982), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"CityID\"");

WriteLiteral("  name=\"CityID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8048), Tuple.Create("\"", 8071)
            
            #line 116 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
                                                                                                                             , Tuple.Create(Tuple.Create("", 8056), Tuple.Create<System.Object, System.Int32>(Model.CityID
            
            #line default
            #line hidden
, 8056), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"SubPlanID\"");

WriteLiteral("  name=\"SubPlanID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8127), Tuple.Create("\"", 8153)
            
            #line 116 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
                                                                                                                                                                                                            , Tuple.Create(Tuple.Create("", 8135), Tuple.Create<System.Object, System.Int32>(Model.SubPlanID
            
            #line default
            #line hidden
, 8135), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"TimingType\"");

WriteLiteral("  name=\"TimingType\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8211), Tuple.Create("\"", 8238)
            
            #line 116 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
                                                                                                                                                                                                                                                                                                , Tuple.Create(Tuple.Create("", 8219), Tuple.Create<System.Object, System.Int32>(Model.TimingType
            
            #line default
            #line hidden
, 8219), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"CreateUnit\"");

WriteLiteral("  name=\"CreateUnit\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8296), Tuple.Create("\"", 8323)
            
            #line 116 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
                                                                                                                                                                                                                                                                                                                                                                                     , Tuple.Create(Tuple.Create("", 8304), Tuple.Create<System.Object, System.Int32>(Model.CreateUnit
            
            #line default
            #line hidden
, 8304), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"StartPeriod\"");

WriteLiteral("  name=\"StartPeriod\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8383), Tuple.Create("\"", 8411)
            
            #line 116 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            , Tuple.Create(Tuple.Create("", 8391), Tuple.Create<System.Object, System.Int32>(Model.StartPeriod
            
            #line default
            #line hidden
, 8391), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"PeriodStr\"");

WriteLiteral("  name=\"PeriodStr\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8467), Tuple.Create("\"", 8493)
            
            #line 116 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                , Tuple.Create(Tuple.Create("", 8475), Tuple.Create<System.Object, System.Int32>(Model.PeriodStr
            
            #line default
            #line hidden
, 8475), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"CreatePeriod\"");

WriteLiteral("  name=\"CreatePeriod\"");

WriteAttribute("value", Tuple.Create(" value=\"", 8555), Tuple.Create("\"", 8584)
            
            #line 116 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        , Tuple.Create(Tuple.Create("", 8563), Tuple.Create<System.Object, System.Int32>(Model.CreatePeriod
            
            #line default
            #line hidden
, 8563), false)
);

WriteLiteral("/>\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 119 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
   Write(RenderPage("~/Areas/Weather/Views/WeatherNodes/Extend/Model_FormHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnSubmit\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-ok\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">确定</a>\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        取消\r\n    </a>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/My97DatePicker/WdatePicker.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/Utils.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        jQuery(function() {\r\n            CheckConditions();\r\njQuery(\'input[nam" +
"e=IsImportToDB]\').bind(\'click\', CheckConditions);\r\njQuery(\'input[name=IsTiming]\'" +
").bind(\'click\', CheckConditions);\r\njQuery(\'#NodeType\').bind(\'change\', CheckCondi" +
"tions);\r\njQuery(\'input[name=TimingType]\').bind(\'click\', CheckConditions);\r\nfunct" +
"ion CheckConditions(){\r\nif((jQuery(\'#NodeType\').val() == \'1\'||jQuery(\'#NodeType\'" +
").val() == \'2\'||jQuery(\'#NodeType\').val() == \'4\'||jQuery(\'#NodeType\').val() == \'" +
"5\'||jQuery(\'#NodeType\').val() == \'6\'||jQuery(\'#NodeType\').val() == \'7\'||jQuery(\'" +
"#NodeType\').val() == \'8\'||jQuery(\'#NodeType\').val() == \'10\')&&IsInCheckBox(docum" +
"ent.myForm.IsTiming,\'1\')&&IsInCheckBox(document.myForm.TimingType,\'0\')&&(IsInChe" +
"ckBox(document.myForm.IsImportToDB,\'0\')||IsInCheckBox(document.myForm.IsImportTo" +
"DB,\'1\'))){\r\njQuery(\'#Container_CreatePeriod\').show();\r\n} \r\nelse{ \r\njQuery(\'#Cont" +
"ainer_CreatePeriod\').hide();\r\n} \r\nif((jQuery(\'#NodeType\').val() == \'1\'||jQuery(\'" +
"#NodeType\').val() == \'2\'||jQuery(\'#NodeType\').val() == \'4\'||jQuery(\'#NodeType\')." +
"val() == \'5\'||jQuery(\'#NodeType\').val() == \'6\'||jQuery(\'#NodeType\').val() == \'7\'" +
"||jQuery(\'#NodeType\').val() == \'8\'||jQuery(\'#NodeType\').val() == \'10\')&&IsInChec" +
"kBox(document.myForm.IsTiming,\'1\')&&(IsInCheckBox(document.myForm.IsImportToDB,\'" +
"0\')||IsInCheckBox(document.myForm.IsImportToDB,\'1\'))){\r\njQuery(\'#Container_Creat" +
"eUnit\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_CreateUnit\').hide();\r\n} \r\nif((jQ" +
"uery(\'#NodeType\').val() == \'1\'||jQuery(\'#NodeType\').val() == \'2\'||jQuery(\'#NodeT" +
"ype\').val() == \'4\'||jQuery(\'#NodeType\').val() == \'5\'||jQuery(\'#NodeType\').val() " +
"== \'6\'||jQuery(\'#NodeType\').val() == \'7\'||jQuery(\'#NodeType\').val() == \'8\'||jQue" +
"ry(\'#NodeType\').val() == \'10\')&&IsInCheckBox(document.myForm.IsImportToDB,\'1\')){" +
"\r\njQuery(\'#Container_Deley\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_Deley\').hid" +
"e();\r\n} \r\nif((jQuery(\'#NodeType\').val() == \'1\'||jQuery(\'#NodeType\').val() == \'2\'" +
")){\r\njQuery(\'#Container_Description\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_De" +
"scription\').hide();\r\n} \r\nif((jQuery(\'#NodeType\').val() == \'1\'||jQuery(\'#NodeType" +
"\').val() == \'2\'||jQuery(\'#NodeType\').val() == \'8\'||jQuery(\'#NodeType\').val() == " +
"\'4\'||jQuery(\'#NodeType\').val() == \'5\'||jQuery(\'#NodeType\').val() == \'6\'||jQuery(" +
"\'#NodeType\').val() == \'7\'||jQuery(\'#NodeType\').val() == \'10\')){\r\njQuery(\'#Contai" +
"ner_IsImportToDB\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_IsImportToDB\').hide()" +
";\r\n} \r\nif((jQuery(\'#NodeType\').val() == \'1\'||jQuery(\'#NodeType\').val() == \'2\'||j" +
"Query(\'#NodeType\').val() == \'4\'||jQuery(\'#NodeType\').val() == \'5\'||jQuery(\'#Node" +
"Type\').val() == \'6\'||jQuery(\'#NodeType\').val() == \'7\'||jQuery(\'#NodeType\').val()" +
" == \'8\'||jQuery(\'#NodeType\').val() == \'10\')&&(IsInCheckBox(document.myForm.IsImp" +
"ortToDB,\'1\')||IsInCheckBox(document.myForm.IsImportToDB,\'0\'))){\r\njQuery(\'#Contai" +
"ner_IsTiming\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_IsTiming\').hide();\r\n} \r\ni" +
"f((jQuery(\'#NodeType\').val() == \'1\'||jQuery(\'#NodeType\').val() == \'2\'||jQuery(\'#" +
"NodeType\').val() == \'4\'||jQuery(\'#NodeType\').val() == \'5\'||jQuery(\'#NodeType\').v" +
"al() == \'6\'||jQuery(\'#NodeType\').val() == \'7\'||jQuery(\'#NodeType\').val() == \'8\'|" +
"|jQuery(\'#NodeType\').val() == \'10\')&&IsInCheckBox(document.myForm.IsImportToDB,\'" +
"0\')){\r\njQuery(\'#Container_NodePath\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_Nod" +
"ePath\').hide();\r\n} \r\nif((jQuery(\'#NodeType\').val() == \'1\'||jQuery(\'#NodeType\').v" +
"al() == \'2\')){\r\njQuery(\'#Container_NodePicUrl\').show();\r\n} \r\nelse{ \r\njQuery(\'#Co" +
"ntainer_NodePicUrl\').hide();\r\n} \r\nif(IsInCheckBox(document.myForm.TimingType,\'1\'" +
")&&IsInCheckBox(document.myForm.IsTiming,\'1\')&&(jQuery(\'#NodeType\').val() == \'1\'" +
"||jQuery(\'#NodeType\').val() == \'2\'||jQuery(\'#NodeType\').val() == \'4\'||jQuery(\'#N" +
"odeType\').val() == \'5\'||jQuery(\'#NodeType\').val() == \'6\'||jQuery(\'#NodeType\').va" +
"l() == \'7\'||jQuery(\'#NodeType\').val() == \'8\'||jQuery(\'#NodeType\').val() == \'10\')" +
"&&(IsInCheckBox(document.myForm.IsImportToDB,\'0\')||IsInCheckBox(document.myForm." +
"IsImportToDB,\'1\'))){\r\njQuery(\'#Container_PeriodStr\').show();\r\n} \r\nelse{ \r\njQuery" +
"(\'#Container_PeriodStr\').hide();\r\n} \r\nif(IsInCheckBox(document.myForm.TimingType" +
",\'0\')&&IsInCheckBox(document.myForm.IsTiming,\'1\')&&(jQuery(\'#NodeType\').val() ==" +
" \'1\'||jQuery(\'#NodeType\').val() == \'2\'||jQuery(\'#NodeType\').val() == \'4\'||jQuery" +
"(\'#NodeType\').val() == \'5\'||jQuery(\'#NodeType\').val() == \'6\'||jQuery(\'#NodeType\'" +
").val() == \'7\'||jQuery(\'#NodeType\').val() == \'8\'||jQuery(\'#NodeType\').val() == \'" +
"10\')&&(IsInCheckBox(document.myForm.IsImportToDB,\'0\')||IsInCheckBox(document.myF" +
"orm.IsImportToDB,\'1\'))){\r\njQuery(\'#Container_StartPeriod\').show();\r\n} \r\nelse{ \r\n" +
"jQuery(\'#Container_StartPeriod\').hide();\r\n} \r\nif(IsInCheckBox(document.myForm.Is" +
"Timing,\'1\')&&(jQuery(\'#NodeType\').val() == \'1\'||jQuery(\'#NodeType\').val() == \'2\'" +
"||jQuery(\'#NodeType\').val() == \'4\'||jQuery(\'#NodeType\').val() == \'5\'||jQuery(\'#N" +
"odeType\').val() == \'6\'||jQuery(\'#NodeType\').val() == \'7\'||jQuery(\'#NodeType\').va" +
"l() == \'8\'||jQuery(\'#NodeType\').val() == \'10\')&&(IsInCheckBox(document.myForm.Is" +
"ImportToDB,\'0\')||IsInCheckBox(document.myForm.IsImportToDB,\'1\'))){\r\njQuery(\'#Con" +
"tainer_TimingType\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_TimingType\').hide();" +
"\r\n} \r\nif((jQuery(\'#NodeType\').val() == \'1\'||jQuery(\'#NodeType\').val() == \'2\'||jQ" +
"uery(\'#NodeType\').val() == \'4\'||jQuery(\'#NodeType\').val() == \'5\'||jQuery(\'#NodeT" +
"ype\').val() == \'6\'||jQuery(\'#NodeType\').val() == \'7\'||jQuery(\'#NodeType\').val() " +
"== \'8\')){\r\njQuery(\'#Container_Tips\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_Tip" +
"s\').hide();\r\n} \r\njQuery(\'fieldset\').show(); \r\njQuery(\"fieldset\").each(function()" +
"{ \r\nif(jQuery(\'tr\',this).length>0){\r\nif(jQuery(\'tr:visible\',this).length>0){jQue" +
"ry(this).show()} else{jQuery(this).hide()}\r\n}\r\n});\r\n}\r\n;\r\n        });\r\n    </scr" +
"ipt>\r\n");

WriteLiteral("    ");

            
            #line 223 "..\..\Areas\Weather\Views\WeatherNodes\_\Edit.cshtml"
Write(RenderPage("~/Areas/Weather/Views/WeatherNodes/Extend/Model_FormJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
