#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage.Entity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Typhoon/Views/TyphoonPath/_/Create.cshtml")]
    public partial class _Areas_Typhoon_Views_TyphoonPath___Create_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Typhoon_Views_TyphoonPath___Create_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\Typhoon\Views\TyphoonPath\_\Create.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------
    ViewBag.Title="新建台风路径";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #F6F6F6; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/Typhoon/TyphoonPath/Create\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_TyphoonID\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">台风编号：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"TyphoonID\"");

WriteLiteral(" name=\"TyphoonID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 840), Tuple.Create("\"", 866)
            
            #line 22 "..\..\Areas\Typhoon\Views\TyphoonPath\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 848), Tuple.Create<System.Object, System.Int32>(Model.TyphoonID
            
            #line default
            #line hidden
, 848), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"20\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">台风时间：</td><td>&nbsp;    <input");

WriteLiteral(" class=\"Wdate\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" onClick=\"WdatePicker({dateFmt:\'yyyy-MM-dd HH:mm:ss\'})\"");

WriteLiteral(" id=\"PathTime\"");

WriteLiteral(" name=\"PathTime\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1127), Tuple.Create("\"", 1208)
            
            #line 24 "..\..\Areas\Typhoon\Views\TyphoonPath\_\Create.cshtml"
                                                                                          , Tuple.Create(Tuple.Create("", 1135), Tuple.Create<System.Object, System.Int32>(Model.PathTime==null?"":Model.PathTime.ToString("yyyy-MM-dd HH:mm:ss")
            
            #line default
            #line hidden
, 1135), false)
);

WriteLiteral(" style=\"width:135px;\"");

WriteLiteral(">\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_Longitude\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">台风中心经度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Longitude\"");

WriteLiteral(" name=\"Longitude\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1372), Tuple.Create("\"", 1398)
            
            #line 29 "..\..\Areas\Typhoon\Views\TyphoonPath\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1380), Tuple.Create<System.Object, System.Int32>(Model.Longitude
            
            #line default
            #line hidden
, 1380), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"8\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">台风中心纬度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Latitude\"");

WriteLiteral(" name=\"Latitude\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1573), Tuple.Create("\"", 1598)
            
            #line 32 "..\..\Areas\Typhoon\Views\TyphoonPath\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1581), Tuple.Create<System.Object, System.Int32>(Model.Latitude
            
            #line default
            #line hidden
, 1581), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"8\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_Hours\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">时效：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Hours\"");

WriteLiteral(" name=\"Hours\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1797), Tuple.Create("\"", 1819)
            
            #line 37 "..\..\Areas\Typhoon\Views\TyphoonPath\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1805), Tuple.Create<System.Object, System.Int32>(Model.Hours
            
            #line default
            #line hidden
, 1805), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"4\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">中心气压：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"CenterAirPressure\"");

WriteLiteral(" name=\"CenterAirPressure\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2010), Tuple.Create("\"", 2044)
            
            #line 40 "..\..\Areas\Typhoon\Views\TyphoonPath\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2018), Tuple.Create<System.Object, System.Int32>(Model.CenterAirPressure
            
            #line default
            #line hidden
, 2018), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"8\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_MaxWindSpeed\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">最大风速：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"MaxWindSpeed\"");

WriteLiteral(" name=\"MaxWindSpeed\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2266), Tuple.Create("\"", 2295)
            
            #line 45 "..\..\Areas\Typhoon\Views\TyphoonPath\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2274), Tuple.Create<System.Object, System.Int32>(Model.MaxWindSpeed
            
            #line default
            #line hidden
, 2274), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"8\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">移动方向：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"MoveHeading\"");

WriteLiteral(" name=\"MoveHeading\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2474), Tuple.Create("\"", 2502)
            
            #line 48 "..\..\Areas\Typhoon\Views\TyphoonPath\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2482), Tuple.Create<System.Object, System.Int32>(Model.MoveHeading
            
            #line default
            #line hidden
, 2482), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"4\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_MoveSpeeding\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">移动速度：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"MoveSpeeding\"");

WriteLiteral(" name=\"MoveSpeeding\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2724), Tuple.Create("\"", 2753)
            
            #line 53 "..\..\Areas\Typhoon\Views\TyphoonPath\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2732), Tuple.Create<System.Object, System.Int32>(Model.MoveSpeeding
            
            #line default
            #line hidden
, 2732), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"8\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">台风中心七级半径：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"CenterSevenRadius\"");

WriteLiteral(" name=\"CenterSevenRadius\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2948), Tuple.Create("\"", 2982)
            
            #line 56 "..\..\Areas\Typhoon\Views\TyphoonPath\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2956), Tuple.Create<System.Object, System.Int32>(Model.CenterSevenRadius
            
            #line default
            #line hidden
, 2956), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"8\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_CenterTenRadius\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">台风中心十级半径：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"CenterTenRadius\"");

WriteLiteral(" name=\"CenterTenRadius\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3217), Tuple.Create("\"", 3249)
            
            #line 61 "..\..\Areas\Typhoon\Views\TyphoonPath\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3225), Tuple.Create<System.Object, System.Int32>(Model.CenterTenRadius
            
            #line default
            #line hidden
, 3225), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"8\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">ReportCenter：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ReportCenter\"");

WriteLiteral(" name=\"ReportCenter\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3438), Tuple.Create("\"", 3467)
            
            #line 64 "..\..\Areas\Typhoon\Views\TyphoonPath\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3446), Tuple.Create<System.Object, System.Int32>(Model.ReportCenter
            
            #line default
            #line hidden
, 3446), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"20\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 70 "..\..\Areas\Typhoon\Views\TyphoonPath\_\Create.cshtml"
   Write(RenderPage("~/Areas/Typhoon/Views/TyphoonPath/Extend/Model_FormHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnSubmit\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-ok\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">确定</a>\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        取消\r\n    </a>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/My97DatePicker/WdatePicker.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/Utils.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        jQuery(function() {
            CheckConditions();
function CheckConditions(){
jQuery('fieldset').show(); 
jQuery(""fieldset"").each(function(){ 
if(jQuery('tr',this).length>0){
if(jQuery('tr:visible',this).length>0){jQuery(this).show()} else{jQuery(this).hide()}
}
});
}
;
        });
    </script>
");

WriteLiteral("    ");

            
            #line 98 "..\..\Areas\Typhoon\Views\TyphoonPath\_\Create.cshtml"
Write(RenderPage("~/Areas/Typhoon/Views/TyphoonPath/Extend/Model_FormJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
