#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    
    #line 1 "..\..\Views\Shared\_Layout.cshtml"
    using System.Collections;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    
    #line 2 "..\..\Views\Shared\_Layout.cshtml"
    using Yamon.Module.SiteManage.DAL;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\_Layout.cshtml"
    using Yamon.Module.SiteManage.Entity;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\_Layout.cshtml"
    using Yamon.Module.UCenter.DAL;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Shared\_Layout.cshtml"
  
    MenuDAL menuDal = new MenuDAL();
    RolePurviewDAL rolePurviewDal = new RolePurviewDAL();
    string roleId = CookieHelper.GetCookie("RoleIDList");
    ArrayList purviewList = rolePurviewDal.GetPurviewListByRoleID(roleId);
    ViewBag.LeftMenuList = menuDal.GetMyTreeMenuList(roleId, purviewList);
    VersionInfoDAL versionDal=new VersionInfoDAL();
    string menuId = RequestHelper.GetRequestString("Menu");
    List<Menu> parentMenuList = new List<Menu>();
    if (!string.IsNullOrEmpty(menuId))
    {
        List<Menu> menuList = menuDal.GetMyMenuList(roleId, purviewList);
        Menu menuInfo = menuList.FindLast(o => o.MenuID == menuId);
        if (menuInfo != null)
        {
            ViewBag.Title = menuInfo.MenuName;
            ViewBag.TitleTips = menuInfo.Tips;
            parentMenuList = menuDal.GetParentPathList(menuList,menuInfo.MenuID,false);
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(">\r\n    <title>");

            
            #line 32 "..\..\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 32 "..\..\Views\Shared\_Layout.cshtml"
                        Write(ViewBag.Config.SiteName);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <!-- Tell the browser to be responsive to screen width -->\r\n    <me" +
"ta");

WriteLiteral(" content=\"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no\"" +
"");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" href=\"/Resources/JsLib/bootstrap/css/bootstrap.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/Resources/JsLib/font-awesome/css/font-awesome.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/Static/AdminLTE2/css/AdminLTE.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" href=\"/Resources/JsLib/jquery-easyui/themes/bootstrap/easyui.css\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" href=\"/Resources/JsLib/jquery-easyui/themes/icon.css\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/Static/v1/css/common.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/Static/AdminLTE2/css/skins/_all-skins.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/Static/Home/css/Public.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.min.js\"");

WriteLiteral("></script>\r\n    <!--[if lt IE 9]>\r\n    <script");

WriteLiteral(" src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"");

WriteLiteral("></script>\r\n    <![endif]-->\r\n");

WriteLiteral("    ");

            
            #line 48 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("styles", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var config = {};\r\n        config.ResourcesPath = \"");

            
            #line 51 "..\..\Views\Shared\_Layout.cshtml"
                           Write(Url.Content("~/Resources/"));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n        config.ViewPath = \"");

            
            #line 52 "..\..\Views\Shared\_Layout.cshtml"
                      Write(Url.Content("~/Static/"));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n        config.BaseURI = \"");

            
            #line 53 "..\..\Views\Shared\_Layout.cshtml"
                     Write(Url.Content("~/"));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n        config.RootURI = \"");

            
            #line 54 "..\..\Views\Shared\_Layout.cshtml"
                     Write(RequestHelper.GetRootURI());

            
            #line default
            #line hidden
WriteLiteral("\";\r\n\r\n        var myPage = {};\r\n        myPage.action = \'");

            
            #line 57 "..\..\Views\Shared\_Layout.cshtml"
                     Write(ViewContext.RouteData.Values["action"].ToString());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        myPage.controller = \'");

            
            #line 58 "..\..\Views\Shared\_Layout.cshtml"
                         Write(ViewContext.RouteData.Values["controller"].ToString());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        myPage.id = \'");

            
            #line 59 "..\..\Views\Shared\_Layout.cshtml"
                 Write(ViewContext.RouteData.Values["id"]);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        myPage.frame = \'");

            
            #line 60 "..\..\Views\Shared\_Layout.cshtml"
                    Write(Request["Frame"]);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n\r\n    </script>\r\n</head>\r\n<body");

WriteAttribute("class", Tuple.Create(" class=\"", 3032), Tuple.Create("\"", 3108)
, Tuple.Create(Tuple.Create("", 3040), Tuple.Create("hold-transition", 3040), true)
            
            #line 64 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create(" ", 3055), Tuple.Create<System.Object, System.Int32>(CookieHelper.GetCookie("SkinName")
            
            #line default
            #line hidden
, 3056), false)
, Tuple.Create(Tuple.Create(" ", 3093), Tuple.Create("layout-top-nav", 3094), true)
);

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"wrapper\"");

WriteLiteral(">\r\n        <header");

WriteLiteral(" class=\"main-header\"");

WriteLiteral(">\r\n            <nav");

WriteLiteral(" class=\"navbar navbar-static-top\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" href=\"/\"");

WriteLiteral(" class=\"logo\"");

WriteLiteral(">\r\n                    <!-- mini logo for sidebar mini 50x50 pixels -->\r\n        " +
"            <span");

WriteLiteral(" class=\"logo-mini\"");

WriteLiteral("><b>A</b>pp</span>\r\n                    <!-- logo for regular state and mobile de" +
"vices -->\r\n                    <span");

WriteLiteral(" class=\"logo-lg\"");

WriteLiteral(">");

            
            #line 72 "..\..\Views\Shared\_Layout.cshtml"
                                      Write(ViewBag.Config.SiteName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </a>\r\n                <div");

WriteLiteral(" class=\"navbar-custom-menu\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 76 "..\..\Views\Shared\_Layout.cshtml"
                   Write(RenderPage("Navigation.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <!-- User Account: style can be found in dropdown.less " +
"-->\r\n                        <li");

WriteLiteral(" id=\"control-sidebar\"");

WriteLiteral(" class=\"dropdown user user-menu\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(">\r\n                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4043), Tuple.Create("\"", 4123)
            
            #line 80 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 4049), Tuple.Create<System.Object, System.Int32>(CookieHelper.GetCookie("UserFace", "/Static/AdminLTE2/img/avatar5.png")
            
            #line default
            #line hidden
, 4049), false)
);

WriteLiteral(" class=\"user-image\"");

WriteLiteral(" alt=\"User Image\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"hidden-xs\"");

WriteLiteral(">");

            
            #line 81 "..\..\Views\Shared\_Layout.cshtml"
                                                    Write(CookieHelper.GetCookie("UserName"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                            </a>\r\n                            <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(">\r\n                                <!-- User image -->\r\n                         " +
"       <li");

WriteLiteral(" class=\"user-header\"");

WriteLiteral(">\r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4506), Tuple.Create("\"", 4586)
            
            #line 86 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 4512), Tuple.Create<System.Object, System.Int32>(CookieHelper.GetCookie("UserFace", "/Static/AdminLTE2/img/avatar5.png")
            
            #line default
            #line hidden
, 4512), false)
);

WriteLiteral(" class=\"img-circle\"");

WriteLiteral(" alt=\"User Image\"");

WriteLiteral(">\r\n                                    <p>\r\n");

WriteLiteral("                                        ");

            
            #line 88 "..\..\Views\Shared\_Layout.cshtml"
                                    Write(CookieHelper.GetCookie("TrueName"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        ");

WriteLiteral("\r\n                                    </p>\r\n                                </li>" +
"\r\n                                <!-- Menu Body -->\r\n                          " +
"      ");

WriteLiteral("\r\n                                <!-- Menu Footer-->\r\n                          " +
"      <li");

WriteLiteral(" class=\"user-footer\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(">\r\n                                        <a");

WriteLiteral(" id=\"editpass\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(" class=\"btn btn-default btn-flat\"");

WriteLiteral(">修改密码</a>\r\n                                    </div>\r\n                          " +
"          <div");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n                                        <a");

WriteLiteral(" id=\"loginOut\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(" class=\"btn btn-default btn-flat\"");

WriteLiteral(">退出</a>\r\n                                    </div>\r\n                            " +
"    </li>\r\n                            </ul>\r\n                        </li>\r\n   " +
"                     <li>\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-toggle=\"control-sidebar\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-gears\"");

WriteLiteral("></i></a>\r\n                        </li>\r\n                    </ul>\r\n            " +
"    </div>\r\n            </nav>\r\n    </header>\r\n\r\n        <!-- Content Wrapper. C" +
"ontains page content -->\r\n        <div");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(">\r\n");

            
            #line 127 "..\..\Views\Shared\_Layout.cshtml"
            
            
            #line default
            #line hidden
            
            #line 127 "..\..\Views\Shared\_Layout.cshtml"
             if (!string.IsNullOrEmpty(menuId))
            {

            
            #line default
            #line hidden
WriteLiteral("                <!-- Content Header (Page header) -->\r\n");

WriteLiteral("                <section");

WriteLiteral(" class=\"content-header\"");

WriteLiteral(">\r\n                    <h1>\r\n");

WriteLiteral("                        ");

            
            #line 132 "..\..\Views\Shared\_Layout.cshtml"
                    Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <small>");

            
            #line 133 "..\..\Views\Shared\_Layout.cshtml"
                           Write(ViewBag.Tips);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n                    </h1>\r\n                    <ol");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n                        <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-dashboard\"");

WriteLiteral("></i>首页</a></li>\r\n");

            
            #line 137 "..\..\Views\Shared\_Layout.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 137 "..\..\Views\Shared\_Layout.cshtml"
                         foreach (var menu in parentMenuList)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">");

            
            #line 139 "..\..\Views\Shared\_Layout.cshtml"
                                        Write(menu.MenuName);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");

            
            #line 140 "..\..\Views\Shared\_Layout.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">");

            
            #line 141 "..\..\Views\Shared\_Layout.cshtml"
                                       Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                    </ol>\r\n                </section>\r\n");

            
            #line 144 "..\..\Views\Shared\_Layout.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <!-- Main content -->\r\n            <section");

WriteLiteral(" class=\"content\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 147 "..\..\Views\Shared\_Layout.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </section>\r\n        </div>\r\n            <!-- /.content-wrapper -->\r" +
"\n            <footer");

WriteLiteral(" class=\"main-footer\"");

WriteLiteral(" style=\"height: 30px; padding: 5px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"pull-right hidden-xs\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"/SiteManage/VersionInfo/Version\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral("><b>当前版本：</b>");

            
            #line 153 "..\..\Views\Shared\_Layout.cshtml"
                                                                                      Write(versionDal.GetVersionString());

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                </div>\r\n                <strong>Copyright &copy; 2014-2016 " +
"");

WriteLiteral("</strong> All rights\r\n                reserved.\r\n            </footer>\r\n         " +
"   <!-- Control Sidebar -->\r\n            <aside");

WriteLiteral(" class=\"control-sidebar control-sidebar-dark\"");

WriteLiteral(">\r\n                <!-- Create the tabs -->\r\n                <!-- Tab panes -->\r\n" +
"                <div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(" id=\"control-sidebar-home-tab\"");

WriteLiteral(@">
                    <!-- Home tab content -->
                </div>
            </aside>
            <!-- /.control-sidebar -->
            <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
            <div class=""control-sidebar-bg""></div>
        </div>
    <!-- ./wrapper -->
    <!-- Bootstrap 3.3.5 -->
    <script src=""/Resources/JsLib/bootstrap/js/bootstrap.min.js""></script>
    <script src=""/Resources/JsLib/slimScroll/jquery.slimscroll.min.js""></script>
    <script src=""/Resources/JsLib/fastclick/fastclick.min.js""></script>
    <!-- FastClick -->
    <!-- AdminLTE App -->
    <script src=""/Static/AdminLTE2/js/app.js""></script>
    <!-- AdminLTE for demo purposes -->
    <script src=""/Static/AdminLTE2/js/demo.js""></script>
    <script type=""text/javascript"" src=""/Resources/JsLib/jquery-easyui/jquery.easyui.min.js""></script>
    <script type=""text/javascript"" src=""/Resources/JsLib/jquery-easyui/locale/easyui-lang-zh_CN.js""></script>

    <!--弹出窗体-->
    <div id=""dialogDiv"" style=""overflow:hidden"">
    </div>
    <script src=""/Static/v1/js/common.js""></script>
");

WriteLiteral("    ");

            
            #line 188 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 189 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts2", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 190 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts_toolbar", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
