#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    
    #line 2 "..\..\Views\Shared\_SimpleLayout.cshtml"
    using Yamon.Module.SiteManage.DAL;
    
    #line default
    #line hidden
    
    #line 1 "..\..\Views\Shared\_SimpleLayout.cshtml"
    using Yamon.Module.SiteManage.Entity;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_SimpleLayout.cshtml")]
    public partial class _Views_Shared__SimpleLayout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__SimpleLayout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <title>");

            
            #line 9 "..\..\Views\Shared\_SimpleLayout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 9 "..\..\Views\Shared\_SimpleLayout.cshtml"
                        Write(ViewBag.Config.SiteName);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/Resources/JsLib/jquery.min.js\"");

WriteLiteral("></script>\r\n");

WriteLiteral("    ");

            
            #line 11 "..\..\Views\Shared\_SimpleLayout.cshtml"
Write(RenderSection("styles", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var config = {};\r\n    config.ResourcesPath = \"");

            
            #line 14 "..\..\Views\Shared\_SimpleLayout.cshtml"
                       Write(Url.Content("/Resources/"));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n    config.ViewPath = \"");

            
            #line 15 "..\..\Views\Shared\_SimpleLayout.cshtml"
                  Write(Url.Content("/Static/"));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n    config.BaseURI = \"");

            
            #line 16 "..\..\Views\Shared\_SimpleLayout.cshtml"
                 Write(Url.Content("/"));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n    config.RootURI = \"");

            
            #line 17 "..\..\Views\Shared\_SimpleLayout.cshtml"
                 Write(RequestHelper.GetRootURI());

            
            #line default
            #line hidden
WriteLiteral("\";\r\n\r\n    var myPage = {};\r\n    myPage.action = \'");

            
            #line 20 "..\..\Views\Shared\_SimpleLayout.cshtml"
                 Write(ViewContext.RouteData.Values["action"].ToString());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    myPage.controller = \'");

            
            #line 21 "..\..\Views\Shared\_SimpleLayout.cshtml"
                     Write(ViewContext.RouteData.Values["controller"].ToString());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    myPage.id = \'");

            
            #line 22 "..\..\Views\Shared\_SimpleLayout.cshtml"
             Write(ViewContext.RouteData.Values["id"]);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    </script>\r\n</head>\r\n<body>\r\n");

WriteLiteral("    ");

            
            #line 26 "..\..\Views\Shared\_SimpleLayout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    <!--弹出窗体-->\r\n    <div");

WriteLiteral(" id=\"dialogDiv\"");

WriteLiteral(">\r\n    </div>\r\n");

WriteLiteral("    ");

            
            #line 30 "..\..\Views\Shared\_SimpleLayout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
