#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 23 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
    using System.Data;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 24 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
    using System.Text;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage.Entity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Typhoon/Views/TyphoonName/_/EditGrid.cshtml")]
    public partial class _Areas_Typhoon_Views_TyphoonName___EditGrid_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Typhoon_Views_TyphoonName___EditGrid_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" id=\"tt\"");

WriteLiteral("></div>\r\n");

            
            #line 16 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
Write(RenderPage("~/Areas/Typhoon/Views/TyphoonName/Extend/Model_GridHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" id=\"toolbar\"");

WriteLiteral(" style=\"padding: 5px; height: auto\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"searchForm\"");

WriteLiteral(" name=\"searchForm\"");

WriteLiteral(" action=\"\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n");

            
            #line 19 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
        
            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
         foreach (ToolBar tool in ViewBag.ToolbarList)
{

            
            #line default
            #line hidden
WriteLiteral("    <a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteAttribute("id", Tuple.Create(" id=\"", 710), Tuple.Create("\"", 732)
            
            #line 21 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
, Tuple.Create(Tuple.Create("", 715), Tuple.Create<System.Object, System.Int32>(tool.ToolBarID
            
            #line default
            #line hidden
, 715), false)
);

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteAttribute("iconcls", Tuple.Create(" iconcls=\"", 759), Tuple.Create("\"", 786)
            
            #line 21 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
             , Tuple.Create(Tuple.Create("", 769), Tuple.Create<System.Object, System.Int32>(tool.ClassName
            
            #line default
            #line hidden
, 769), false)
);

WriteLiteral(" plain=\"true\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 800), Tuple.Create("\"", 874)
, Tuple.Create(Tuple.Create("", 810), Tuple.Create("T_", 810), true)
            
            #line 21 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
                                                        , Tuple.Create(Tuple.Create("", 812), Tuple.Create<System.Object, System.Int32>(tool.ToolBarID.Replace("-","")
            
            #line default
            #line hidden
, 812), false)
, Tuple.Create(Tuple.Create("", 845), Tuple.Create("ClickHandler();return", 845), true)
, Tuple.Create(Tuple.Create(" ", 866), Tuple.Create("false;", 867), true)
, Tuple.Create(Tuple.Create(" ", 873), Tuple.Create("", 873), true)
);

WriteLiteral(">");

            
            #line 21 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
                                                                                                                                                                                                  Write(tool.ToolBarName);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 22 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
}

            
            #line default
            #line hidden
DefineSection("scripts_toolbar", () => {

WriteLiteral("\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n");

            
            #line 28 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
    
            
            #line default
            #line hidden
            
            #line 28 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
     foreach (ToolBar tool in ViewBag.ToolbarList)
    {

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral(" function T_");

            
            #line 30 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
              Write(tool.ToolBarID.Replace("-",""));

            
            #line default
            #line hidden
WriteLiteral("ClickHandler() {\r\n");

WriteLiteral("    ");

WriteLiteral("     ");

            
            #line 31 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
      Write(Html.Raw(tool.OnClick));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

WriteLiteral("     return false;\r\n");

WriteLiteral("    ");

WriteLiteral(" }\r\n");

            
            #line 34 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</script>\r\n");

});

WriteLiteral("\r\n        <span");

WriteLiteral(" id=\"span_name_en\"");

WriteLiteral("  style=\"height:24px;display: inline-block;\"");

WriteLiteral(">台风英文名称：<input");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"name_en\"");

WriteLiteral(" name=\"name_en\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" style=\"width:100px\"");

WriteLiteral(" /></span>\r\n<span");

WriteLiteral(" id=\"span_name_cn\"");

WriteLiteral("  style=\"height:24px;display: inline-block;\"");

WriteLiteral(">台风中文名称：<input");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"name_cn\"");

WriteLiteral(" name=\"name_cn\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" style=\"width:100px\"");

WriteLiteral(" /></span>\r\n<span");

WriteLiteral(" id=\"span_country\"");

WriteLiteral("  style=\"height:24px;display: inline-block;\"");

WriteLiteral(">国家：<input");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"country\"");

WriteLiteral(" name=\"country\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" style=\"width:100px\"");

WriteLiteral(" /></span>\r\n\r\n            <a");

WriteLiteral(" id=\"btnSubmit\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-search\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">查询</a>\r\n            <a");

WriteLiteral(" id=\"btnReset\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-ok\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">清空</a>\r\n\r\n    </form>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.query.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery-easyui-extends/jquery.edatagrid.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/My97DatePicker/WdatePicker.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/GridUtils.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/SmartFormGrid.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/EditGrid.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        var toolbar = '#toolbar';
        var _baseUrl = '/Typhoon/TyphoonName';
var _apiUrl = '/api/Typhoon/TyphoonName';
var _pageUrl = '';
var Data = {
BaseUrl: _baseUrl,
ApiUrl: _apiUrl,
FilterID: '',
DataUrl: _apiUrl + '/EditGrid?'+_pageUrl,
CreateUrl: _baseUrl + '/Create?'+_pageUrl,
EditUrl: _baseUrl + '/Edit/{id}?'+_pageUrl,
ShowUrl: _baseUrl + '/Show/',
BatchDeleteUrl: _apiUrl + '/BatchDelete?'+_pageUrl,
DeleteUrl: _apiUrl + '/Delete?'+_pageUrl,
ModuleID: 'Typhoon',
ModelID: 'TyphoonName',
PageSize: 20,
DialogWidth: 700,
DialogHeight: 600,
FieldShowType_Name_FieldName: '',
TreeField: '',
FieldShowType_Name_Title: '',
ItemName: ""台风名称"",
PrimaryKey: 'id',
SortField: 'id',
OrderType: 'asc',
Height: 0,
UnAutoLoadGrid: ");

            
            #line 85 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
            Write(RequestHelper.GetInt("UnAutoLoadGrid"));

            
            #line default
            #line hidden
WriteLiteral(",\r\ncolumns: [[\r\n");

            
            #line 87 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
 foreach (ToolBar tool in ViewBag.ToolbarColumnList)
{
    if(tool.OrderID < 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("{field: \'");

            
            #line 91 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
               Write(tool.ToolBarID);

            
            #line default
            #line hidden
WriteLiteral("\', title: \'");

            
            #line 91 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
                                           Write(tool.ToolBarName);

            
            #line default
            #line hidden
WriteLiteral("\', sortable: false,width:");

            
            #line 91 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
                                                                                       Write(tool.ToolBarName.Length*15+10);

            
            #line default
            #line hidden
WriteLiteral(",align:\'center\',formatter: function(value, row, index){\r\n");

WriteLiteral("        ");

WriteLiteral("    ");

            
            #line 92 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
         Write(Html.Raw(tool.OnClick));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

WriteLiteral("}},\r\n");

            
            #line 94 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
    }
}

            
            #line default
            #line hidden
WriteLiteral(@"
{field: 'id', title: 'ID', sortable: true,width:100,hidden:true,align:'left'},
{field: 'name_en', title: '台风英文名称', sortable: true,width:100,align:'left',
editor:{type:'validatebox',
options:{
test:1}
}
},
{field: 'name_cn', title: '台风中文名称', sortable: true,width:100,align:'left',
editor:{type:'validatebox',
options:{
test:1}
}
},
{field: 'country', title: '国家', sortable: true,width:100,align:'left',
editor:{type:'validatebox',
options:{
test:1}
}
}
");

            
            #line 116 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
 foreach (ToolBar tool in ViewBag.ToolbarColumnList)
{
    if(tool.OrderID >= 0)
    {

            
            #line default
            #line hidden
WriteLiteral(",{field: \'");

            
            #line 120 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
        Write(tool.ToolBarID);

            
            #line default
            #line hidden
WriteLiteral("\', title: \'");

            
            #line 120 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
                                    Write(tool.ToolBarName);

            
            #line default
            #line hidden
WriteLiteral("\', sortable: false,width:");

            
            #line 120 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
                                                                                Write(tool.ToolBarName.Length*15+10);

            
            #line default
            #line hidden
WriteLiteral(",align:\'center\',formatter: function(value, row, index){\r\n");

WriteLiteral("    ");

            
            #line 121 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
 Write(Html.Raw(tool.OnClick));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("}}\r\n");

            
            #line 123 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
    }
}

            
            #line default
            #line hidden
WriteLiteral("]],\r\nfrozenColumns: [\r\n    [\r\n        {\r\n            field: \'ck\',\r\n            ch" +
"eckbox: true\r\n        }\r\n    ]\r\n],\r\ntoolbar: \'#toolbar\',\r\nsingleSelect: ");

            
            #line 135 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
          Write(RequestHelper.GetBool("SingleSelect",true).ToString().ToLower());

            
            #line default
            #line hidden
WriteLiteral("\r\n}\r\n        Data.QuickCreateActionUrl = Data.ApiUrl + \'/Create?ReturnData=true&\'" +
" + _pageUrl;\r\n        Data.QuickEditActionUrl = Data.ApiUrl + \'/Edit?ReturnData=" +
"true&\' + _pageUrl;\r\n        var newrow=");

            
            #line 139 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
              Write(Html.Raw(ViewData["InsertDefaultValueJson"]));

            
            #line default
            #line hidden
WriteLiteral(";\r\n    </script>\r\n");

            
            #line 141 "..\..\Areas\Typhoon\Views\TyphoonName\_\EditGrid.cshtml"
Write(RenderPage("~/Areas/Typhoon/Views/TyphoonName/Extend/Model_GridJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
