#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Home\LeftMenu.cshtml"
    using System.Data;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Home\LeftMenu.cshtml"
    using Yamon.Framework.Common;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Home\LeftMenu.cshtml"
    using Yamon.Module.SiteManage.Entity;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/LeftMenu.cshtml")]
    public partial class _Views_Home_LeftMenu_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_LeftMenu_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Home\LeftMenu.cshtml"
  
    List<Menu> menuList = (List<Menu>)ViewBag.LeftMenuList;

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"sjjk_left\"");

WriteLiteral(">\r\n\r\n    <div");

WriteLiteral(" class=\"sjjk_con\"");

WriteLiteral(">\r\n");

            
            #line 10 "..\..\Views\Home\LeftMenu.cshtml"
        
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Home\LeftMenu.cshtml"
         foreach (Menu menu in menuList)
        {
            //int level = DataConverter.ToInt(menu["Level"]);
            string menuId = menu.MenuID;

            if (menu.Children == null)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteAttribute("url", Tuple.Create(" url=\"", 448), Tuple.Create("\"", 469)
            
            #line 17 "..\..\Views\Home\LeftMenu.cshtml"
, Tuple.Create(Tuple.Create("", 454), Tuple.Create<System.Object, System.Int32>(menu.LinkUrl
            
            #line default
            #line hidden
, 454), false)
);

WriteLiteral(" class=\"sjjk_left_list location\"");

WriteAttribute("menuid", Tuple.Create(" menuid=\"", 502), Tuple.Create("\"", 518)
            
            #line 17 "..\..\Views\Home\LeftMenu.cshtml"
    , Tuple.Create(Tuple.Create("", 511), Tuple.Create<System.Object, System.Int32>(menuId
            
            #line default
            #line hidden
, 511), false)
);

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"left_icon\"");

WriteLiteral("><span>");

            
            #line 18 "..\..\Views\Home\LeftMenu.cshtml"
                                             Write(menu.MenuName);

            
            #line default
            #line hidden
WriteLiteral("</span></div>\r\n                </div>\r\n");

            
            #line 20 "..\..\Views\Home\LeftMenu.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"sjjk_left_list\"");

WriteAttribute("menuid", Tuple.Create(" menuid=\"", 717), Tuple.Create("\"", 733)
            
            #line 23 "..\..\Views\Home\LeftMenu.cshtml"
, Tuple.Create(Tuple.Create("", 726), Tuple.Create<System.Object, System.Int32>(menuId
            
            #line default
            #line hidden
, 726), false)
);

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"left_icon\"");

WriteLiteral("><span>");

            
            #line 24 "..\..\Views\Home\LeftMenu.cshtml"
                                             Write(menu.MenuName);

            
            #line default
            #line hidden
WriteLiteral("</span></div>\r\n                </div>\r\n");

WriteLiteral("                <ul");

WriteLiteral(" class=\"sjjk_list\"");

WriteAttribute("id", Tuple.Create(" id=\"", 878), Tuple.Create("\"", 895)
, Tuple.Create(Tuple.Create("", 883), Tuple.Create("menu_", 883), true)
            
            #line 26 "..\..\Views\Home\LeftMenu.cshtml"
, Tuple.Create(Tuple.Create("", 888), Tuple.Create<System.Object, System.Int32>(menuId
            
            #line default
            #line hidden
, 888), false)
);

WriteLiteral(">\r\n");

            
            #line 27 "..\..\Views\Home\LeftMenu.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\Home\LeftMenu.cshtml"
                     foreach (Menu subMenu in menu.Children)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <li");

WriteAttribute("url", Tuple.Create(" url=\"", 1011), Tuple.Create("\"", 1035)
            
            #line 29 "..\..\Views\Home\LeftMenu.cshtml"
, Tuple.Create(Tuple.Create("", 1017), Tuple.Create<System.Object, System.Int32>(subMenu.LinkUrl
            
            #line default
            #line hidden
, 1017), false)
);

WriteAttribute("menuid", Tuple.Create(" menuid=\"", 1036), Tuple.Create("\"", 1062)
            
            #line 29 "..\..\Views\Home\LeftMenu.cshtml"
, Tuple.Create(Tuple.Create("", 1045), Tuple.Create<System.Object, System.Int32>(subMenu.MenuID
            
            #line default
            #line hidden
, 1045), false)
);

WriteLiteral(" class=\"location\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"border_center\"");

WriteLiteral(">");

            
            #line 30 "..\..\Views\Home\LeftMenu.cshtml"
                                                   Write(subMenu.MenuName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        </li>\r\n");

            
            #line 32 "..\..\Views\Home\LeftMenu.cshtml"
                        if (subMenu.Children != null)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <ul");

WriteLiteral(" class=\"sjjk_list\"");

WriteAttribute("id", Tuple.Create(" id=\"", 1327), Tuple.Create("\"", 1354)
, Tuple.Create(Tuple.Create("", 1332), Tuple.Create("menu_", 1332), true)
            
            #line 34 "..\..\Views\Home\LeftMenu.cshtml"
, Tuple.Create(Tuple.Create("", 1337), Tuple.Create<System.Object, System.Int32>(subMenu.MenuID
            
            #line default
            #line hidden
, 1337), false)
);

WriteLiteral(" style=\"padding-left: 20px;\"");

WriteLiteral(">\r\n");

            
            #line 35 "..\..\Views\Home\LeftMenu.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Home\LeftMenu.cshtml"
                                 foreach (Menu subMenu2 in subMenu.Children)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <li");

WriteAttribute("url", Tuple.Create(" url=\"", 1538), Tuple.Create("\"", 1563)
            
            #line 37 "..\..\Views\Home\LeftMenu.cshtml"
, Tuple.Create(Tuple.Create("", 1544), Tuple.Create<System.Object, System.Int32>(subMenu2.LinkUrl
            
            #line default
            #line hidden
, 1544), false)
);

WriteAttribute("menuid", Tuple.Create(" menuid=\"", 1564), Tuple.Create("\"", 1591)
            
            #line 37 "..\..\Views\Home\LeftMenu.cshtml"
, Tuple.Create(Tuple.Create("", 1573), Tuple.Create<System.Object, System.Int32>(subMenu2.MenuID
            
            #line default
            #line hidden
, 1573), false)
);

WriteLiteral(" class=\"location\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"border_center\"");

WriteLiteral(">");

            
            #line 38 "..\..\Views\Home\LeftMenu.cshtml"
                                                               Write(subMenu2.MenuName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                    </li>\r\n");

            
            #line 40 "..\..\Views\Home\LeftMenu.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </ul>\r\n");

            
            #line 42 "..\..\Views\Home\LeftMenu.cshtml"
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                </ul>\r\n");

            
            #line 45 "..\..\Views\Home\LeftMenu.cshtml"
            }
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n\r\n");

DefineSection("styles", () => {

WriteLiteral("\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1970), Tuple.Create("\"", 2007)
, Tuple.Create(Tuple.Create("", 1977), Tuple.Create<System.Object, System.Int32>(Href("~/Static/Home/css/shcommon.css")
, 1977), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

});

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var parentId = \"SystemManage\";\r\n        jQuery(function () {\r\n        " +
"    if (navigator.userAgent.indexOf(\"MSIE\") > 0) {\r\n                jQuery(\'.sjj" +
"k_list\').css(\'paddingLeft\', \'5px\');\r\n            }\r\n            jQuery(\"#btnTogg" +
"leMenu\").click(function () {\r\n                parent.toggleMenu();\r\n            " +
"});\r\n            //左侧菜单#416AA3\r\n            jQuery(\'.sjjk_list li\').click(functi" +
"on () {\r\n                jQuery(\'.sjjk_list li\').children(\'.border_center\').css(" +
"\'color\', \'#ea5283\');\r\n                jQuery(this).children(\'.border_center\').cs" +
"s(\'color\', \'#416AA3\');\r\n\r\n                //隐藏其他ul\r\n                //jQuery(thi" +
"s).next(\'ul\').slideDown(\"slow\").siblings(\"ul\").hide();\r\n            });\r\n       " +
"     initState();\r\n            jQuery(\".sjjk_con .sjjk_list:not(:first)\").hide()" +
";\r\n            jQuery(\".sjjk_con .sjjk_left_list\").click(function () {\r\n        " +
"        jQuery(this).next(\'ul\').slideDown(\"slow\").siblings(\"ul\").hide();\r\n      " +
"      });\r\n\r\n            jQuery(\".sjjk_list li\").click(function () {\r\n          " +
"      var name = jQuery(this).next(\"ul\").text();\r\n                if (name.lengt" +
"h > 25) {\r\n                    if (jQuery(this).attr(\'id\') == \'close\') {\r\n      " +
"                  jQuery(this).css(\'background\', \'url(/Static/Home/images/bg.fw_" +
"r2_c1.png) no-repeat 25px center\').attr(\"id\", \'open\');\r\n                        " +
"jQuery(this).next(\'ul\').slideDown(\'slow\');\r\n                    } else {\r\n      " +
"                  jQuery(this).css(\'background\', \'url(/Static/Home/images/bg.fw_" +
"r2_c2.png) no-repeat 25px center\').attr(\"id\", \'close\');\r\n                       " +
" jQuery(this).next(\'ul\').slideUp(\"slow\");\r\n                    }\r\n              " +
"  }\r\n                liclick(jQuery(this));\r\n            });\r\n            resize" +
"Win();\r\n            window.onresize = resizeWin;\r\n            var firstli = jQue" +
"ry(\'body\').find(\".location\")[0];\r\n            if (jQuery(firstli).attr(\"url\")) {" +
"\r\n                liclick(firstli);\r\n            }\r\n\r\n            jQuery(\'.sjjk_" +
"left_list\').click(function () {\r\n                if (jQuery(this).next(\'ul\').chi" +
"ldren(\"li\").size() == 0) {\r\n                    parent.addTab(jQuery(this).text(" +
"), jQuery(this).attr(\"url\"), jQuery(this).attr(\"menuId\") + \"_Frame\");\r\n         " +
"       }\r\n            });\r\n            function liclick(obj) {\r\n                " +
"jQuery(\".sjjk_list li .border_center\").removeClass(\"select_list\");\r\n            " +
"    jQuery(obj).children(\".border_center\").addClass(\"select_list\")\r\n            " +
"    var name = jQuery(obj).next(\"ul\").text();\r\n                if (name.length <" +
"= 25) {\r\n                    parent.addTab(jQuery(obj).text().trim(), jQuery(obj" +
").attr(\"url\"), jQuery(obj).attr(\"menuId\") + \"_Frame\");\r\n                }\r\n     " +
"       }\r\n\r\n            function initState() {\r\n                jQuery(\'.sjjk_li" +
"st ul\').each(function () {\r\n                    var txt = jQuery(this).children(" +
"\"li\").children(\"div\").text();\r\n                    if (txt.length > 0) {\r\n      " +
"                  jQuery(this).prev(\'li\').css(\'background\', \'url(/Static/Home/im" +
"ages/bg.fw_r2_c2.png) no-repeat 25px center\').attr(\'id\', \'close\');\r\n            " +
"        }\r\n                });\r\n            }\r\n        });\r\n        function res" +
"izeWin() {\r\n            var bodyHeight = jQuery(window).height(); //浏览器当前窗口文档bod" +
"y的高度\r\n            var bodyWidth = jQuery(window).width();\r\n            jQuery(\"." +
"sjjk_left\").css(\"height\", bodyHeight);\r\n            jQuery(\".sjjk_con\").css(\"hei" +
"ght\", bodyHeight + 5);\r\n        }\r\n\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
