#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    
    #line 1 "..\..\Views\Home\Login.cshtml"
    using Yamon.Module.SiteManage.DAL;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Login.cshtml")]
    public partial class _Views_Home_Login_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_Login_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Home\Login.cshtml"
  
    Layout = "~/Views/Shared/_SimpleLayout.cshtml";


            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("styles", () => {

WriteLiteral("\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 125), Tuple.Create("\"", 159)
, Tuple.Create(Tuple.Create("", 132), Tuple.Create<System.Object, System.Int32>(Href("~/Static/Home/css/login.css")
, 132), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n        body {\r\n            width:100%;\r\n            background: url(\"");

            
            #line 11 "..\..\Views\Home\Login.cshtml"
                         Write(ViewBag.Config.SiteLogo);

            
            #line default
            #line hidden
WriteLiteral("\") no-repeat left top;\r\n            background-size:100% 100%;\r\n            backg" +
"round-attachment: fixed;\r\n            overflow:hidden;\r\n        }\r\n    </style>\r" +
"\n");

});

WriteLiteral("<div");

WriteLiteral(" class=\"LoginBg\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"LoginTit\"");

WriteLiteral(">\r\n        <img");

WriteLiteral(" src=\"/Static/Home/images/logoTopImg.png\"");

WriteLiteral(" alt=\"用户登录\"");

WriteLiteral(" />\r\n    </div>\r\n    <ul");

WriteLiteral(" class=\"LoginCon\"");

WriteLiteral(">\r\n        <li");

WriteLiteral(" class=\"User\"");

WriteLiteral("><input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"txtName\"");

WriteLiteral(" name=\"txtName\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" /></li>\r\n        <li");

WriteLiteral(" class=\"Password\"");

WriteLiteral("><input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" id=\"txtPwd\"");

WriteLiteral(" name=\"txtPwd\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" /></li>\r\n        <li");

WriteLiteral(" class=\"Login\"");

WriteLiteral("><input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" name=\"\"");

WriteLiteral(" id=\"btn_login\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" class=\"mainbut01\"");

WriteLiteral(" /></li>\r\n    </ul>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 974), Tuple.Create("\"", 1005)
, Tuple.Create(Tuple.Create("", 980), Tuple.Create<System.Object, System.Int32>(Href("~/Static/Home/js/Login.js")
, 980), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(function () {\r\n            var viewModel = new loginViewModel();\r\n  " +
"          viewModel.init();\r\n        });\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
